### ISSUE TITLE
exiv2 aborts with registerNs

### ISSUE THREAD

**Issue by LockOne** [Exiv2/exiv2#1099]
**Describe the bug**
Another crash found along with #1097 with fuzzing
exiv2 got aborted with the following report:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
Aborted (core dumped)
```

**To Reproduce**
./exiv2 -m [exiv2_mo_crash_1.txt](https://github.com/Exiv2/exiv2/files/4185793/exiv2_mo_crash_1.txt) mo [f1.txt](https://github.com/Exiv2/exiv2/files/4185806/f1.txt)
(Just download first exiv2_mo_crash_1.txt file. It seems the second f1.txt file does not matter.)

**Desktop (please complete the following information):**
Ubuntu 16.04, clang 4.0.0

**Additional context**
It seems `parseLine` is passing an empty string to `registerNs` at `exiv2.cpp:1477`
stack trace of the crash execution:
```
#0  0x00007ffff6f0f428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6f1102a in __GI_abort () at abort.c:89
#2  0x00007ffff754984d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff75476b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7547701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7547919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff75703f7 in std::__throw_out_of_range_fmt(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff75dbcf8 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff799c496 in Exiv2::XmpProperties::registerNs (ns="", prefix="Exiff\262.LfkInfo.GPSDa")
    at /home/cheong/subjects/exiv2-0.27.2-Source/src/properties.cpp:2508
#9  0x00000000004199b2 in (anonymous namespace)::parseLine (modifyCmd=..., line="reg Exiff\262.LfkInfo.GPSDa \"", num=1)
    at /home/cheong/subjects/exiv2-0.27.2-Source/src/exiv2.cpp:1477
#10 0x0000000000418a21 in (anonymous namespace)::parseCmdFiles (modifyCmds=std::vector of length 0, capacity 0,
    cmdFiles=std::vector of length 1, capacity 1 = {...}) at /home/cheong/subjects/exiv2-0.27.2-Source/src/exiv2.cpp:1303
#11 0x00000000004175ce in Params::getopt (this=0x65a790, argc=5, Argv=0x7fffffffe328) at /home/cheong/subjects/exiv2-0.27.2-Source/src/exiv2.cpp:1087
#12 0x0000000000412c16 in main (argc=5, argv=0x7fffffffe328) at /home/cheong/subjects/exiv2-0.27.2-Source/src/exiv2.cpp:139
```
Thanks

**Comment by kevinbackhouse** [comment]
This is a bug in command file parsing. It stops exiv2 with an uncaught exception, so it's fairly harmless.

**Comment by clanmills** [comment]
I'm going to reopen this for Exiv2 0.27.3 on branch 0.27-maintenance.
