### ISSUE TITLE
Forgive line-ending mismatches in the python test suite.

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1146]
The new python test suite is failing on MSYS2 when cross compiled on Fedora and running on Windows.  This is caused by line-ending mismatches.

This is discussed here: https://github.com/Exiv2/exiv2/issues/922#issuecomment-610275806

I believe it's possible to modify the sample programs to output LF by calling `setmode()` and putting stdout into binary mode.  https://stackoverflow.com/questions/5813301/how-c-output-lf-to-stdout-without-being-changed-to-cr-lf

Modifying the code in all our sample programs is a brutal approach when the alternative is to modify the python test suite.  The bash test suite is executing correctly as it performs executes `diff` with `diffargs="--strip-trailing-cr"`

I used unix2dos to modify all the python files and was surprised when that fix was not successful.

**Comment by clanmills** [comment]
I think the fix is:
```
diff --git a/tests/system_tests.py b/tests/system_tests.py
index 701b2cbb..1b64c59e 100644
--- a/tests/system_tests.py
+++ b/tests/system_tests.py
@@ -12,7 +12,7 @@ import string
 import unittest
 
 
-if sys.platform == 'win32':
+if sys.platform in [ 'win32', 'msys' , 'cygwin' ]:
     #: invoke subprocess.Popen with shell=True on Windows
     _SUBPROCESS_SHELL = True
 ```

I think that will even cover **wine**!

**Comment by clanmills** [comment]
My fix is good and reveals a new issue.  Many tests fail as follows:
```
======================================================================
FAIL: test_run (bugfixes.redmine.test_issue_841.ThrowOnInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rmills/temp/0.27-maintenance/tests/system_tests.py", line 632, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/rmills/temp/0.27-maintenance/tests/system_tests.py", line 755, in compare_stderr
    msg="Standard error does not match"
  File "/home/rmills/temp/0.27-maintenance/tests/system_tests.py", line 726, in _compare_output
    expected, got, msg=msg
AssertionError: 'Exiv[32 chars]file C:/msys64/home/rmills/temp/0.27-maintenan[55 chars]ta\n' != 'Exiv[32 chars]file /home/rmills/temp/0.27-maintenance/test/d[46 chars]ta\n'
- Exiv2 exception in print action for file C:/msys64/home/rmills/temp/0.27-maintenance/test/data/exiv2-bug841.png:
?                                          ---------
+ Exiv2 exception in print action for file /home/rmills/temp/0.27-maintenance/test/data/exiv2-bug841.png:
  Failed to read image data
 : Standard error does not match
```
There's a path issue here.  You can run a single test with the following syntax:
```
$ cd <exiv2dir>/tests
$ python3 runner.py --verbose bugfixes/redmine/test_issue_841.py 
```

The python test suite is excellent.  Great Job: @D4N  I'll continue to investigate.

**Comment by clanmills** [comment]
This is **very** subtle.  It's not being caused by the test harness, @D4N 's wonderful test harness is correctly detecting this.

It concerns the code in futils.cpp that handles pathnames.  So on the cross-platform build running on msys2:
```
503 MSYS rmills@rmillsmm-w10:~/temp/0.27-maintenance/build_mingw_shared $ bin/exiv2 -vVg exiv2 -g path -g platform -g version
exiv2 0.27.3.9
exiv2=0.27.3
platform=mingw64
version=9.2.1 20190827 (Fedora MinGW 9.2.1-1.fc31) <-- Fedora build
processpath=C:\msys64\home\rmills\temp\0.27-maintenance\build_mingw_shared\bin <--- NATIVE Windows Path
package_name=exiv2
executable=C:\msys64\home\rmills\temp\0.27-maintenance\build_mingw_shared\bin\exiv2.exe
library=C:\msys64\home\rmills\temp\0.27-maintenance\build_mingw_shared\bin\libexiv2.dll
have_unicode_path=1
config_path=C:\Users\rmills\exiv2.ini <--- NATIVE Windows Path
504 MSYS rmills@rmillsmm-w10:~/temp/0.27-maintenance/build_mingw_shared $
```
However on the msys2 build, on the same machine:
```
615 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.3.9-Source/build $ bin/exiv2 -vVg exiv2 -g path -g platform -g version
exiv2 0.27.3.9
exiv2=0.27.3
platform=msys
version=7.4.0  <-- GCC msys2 7.4.0 compiler
processpath=/home/rmills/temp/exiv2-0.27.3.9-Source/build/bin <-- MSYS2 Path
package_name=exiv2
executable=C:\msys64\home\rmills\temp\exiv2-0.27.3.9-Source\build\bin\exiv2.exe
library=C:\msys64\home\rmills\temp\exiv2-0.27.3.9-Source\build\bin\msys-exiv2-27.dll
have_unicode_path=0
config_path=/home/rmills/.exiv2 <--- MSYS2 Path
616 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.3.9-Source/build $
```
This cause the error handler to report on mingw_build_shared:
```
... $ build/bin/exiv2 test/data/exiv2-bug841.png 
 Exiv2 exception in print action for file C:/msys64/home/rmills/temp/0.27-maintenance/test/data/exiv2-bug841.png <--- Native Windows Path
```
And the reference output should be:
```
Exiv2 exception in print action for file /home/rmills/temp/0.27-maintenance/test/data/exiv2-bug841.png:
```
The reference output is correctly generated on MSYS2 when running an MSYS2 build:
```
618 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.3.9-Source $ build/bin/exiv2 test/data/exiv2-bug841.png
Exiv2 exception in print action for file test/data/exiv2-bug841.png: <--- MSYS2 Path
Failed to read image data
619 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.3.9-Source $
```
I will report a different issue concerning this.

It might not be possible to fix this, in which case there are two possibilities:
1) The error handler throws with the leaf name and not the pathname.
2) We leave futils.cpp alone, and put something in the test suite to convert error paths into leaf names.

**Comment by clanmills** [comment]
PR Submitted for line-ending issue.  #1150
