### ISSUE TITLE
Test Localisation

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1278]
Localisation is not tested in the test suite.

It was never added because I didn't know how to use localisation.  Furthermore, I found it almost impossible to build because of dependencies.  Setting up the platform dependencies is now well documented in README.md, or you can use conan.

I documented localisation in README.md for v0.27.  You build localisation with the cmake option `-DEXIV2_ENABLE_NLS=On`.  To use localisation from the command line:

```bash
680 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ env LANG=fr_FR exiv2
exiv2: Une action doit être spécifié
exiv2: Au moins un fichier est nécessaire
Utilisation : exiv2  [ options ] [ action ] fichier ...

Manipulation des métadonnées EXIF issues des images.
681 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $
```

We should skip the test if NLS (natural language support) has not been built.  We detect this with:

```bash
700 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiv2 --version --verbose --grep nls
exiv2 0.27.3
enable_nls=1
701 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```

There are two additional issues.
1. Currently, you must do a `$ sudo make install` and run the installed version of exiv2.  This is simply due to the code in src/exiv2.cpp main() which uses a EXV_ to find the localisation files.  When running in the build directory, this should be `bin/../build/po` (I think.  I've never tried this!).

2. Localisation is not supported on msvc builds.
I don't think this will have any impact as you will detect enable_nls=0.  I was surprised to discover that vcpkg builds with localisation and I have to investigate that:  #1255  We won't delay the PR for this issue for msvc.

**Comment by LeoHsiao1** [comment]
Excuse me, the steps I understand are:
1. Compile Exiv2 with the following command:
    ```sh
    apt install -y gettext
    cd exiv2/
    mkdir build_local && cd build_local
    cmake .. -DCMAKE_BUILD_TYPE=Release
    cmake --build .
    ```
2. Test `env LANG=fr_FR exiv2` to see if the output matches the reference file.

But what I ended up showing was still ASCII:
```sh
leo@Leo:/mnt/d/1/exiv2/build_local$ env LANG=fr_FR bin/exiv2
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
```

**Comment by clanmills** [comment]
1 You'll need `$cmake .. -DEXIV2_ENABLE_NLS=1` to build localisation.  You will need gettext and libintl on the platform.
2 You must install the build to use localisation: `$ sudo make install`
3. The syntax for localisation on Ubuntu is:
```
$ env LANGUAGE=fr_FR exiv2
```

4. Comments:
The reason is that you must install is in `main()` in src/exiv2.cpp.  The code loads the localisation using a compiler constant which refers to the prefix directory.  I haven't studied that code, however it would be very useful to modify that to load from the build-directory. 
```cpp
// Main
int main(int argc, char* const argv[])
{
    Exiv2::XmpParser::initialize();
    ::atexit(Exiv2::XmpParser::terminate);

#ifdef EXV_ENABLE_NLS
    setlocale(LC_ALL, "");
    const std::string localeDir = EXV_LOCALEDIR[0] == '/' ? EXV_LOCALEDIR : (Exiv2::getProcessPath() + EXV_SEPARATOR_STR + EXV_LOCALEDIR);
    bindtextdomain(EXV_PACKAGE_NAME, localeDir.c_str());
    textdomain(EXV_PACKAGE_NAME);
#endif
```

Do not trust `apt` to install exiv2 correctly.  It installs the command-line executable without the library.  You can install the library with `sudo apt install --yes libexiv2-dev`, however it only installs the library and include files.  It does not  install localisation, man pages and some other stuff.  Don't spend time with `apt`.  It's up to the community to fix/support that.

Stay focused on the Exiv2 code.  It would be great to use the localisation which in the build directory.  I don't remember much about localisation, however it is documented in README.md

**Comment by clanmills** [comment]
There's a quick trick to get the localisation to work from the build directory.  You will need the localisation installed in /usr/local/share:

```bash
$ cd exiv2dir
$ mkdir build
$ cd build
$ ln -s /usr/local/share share   # of course
$ cmake .. -DEXIV2_ENABLE_NLS=1
$ make
$ env LANG=fr_FR bin/exiv2
```

You can detect if the localisation files are present with:
```bash
find /usr/local/share -name exiv2.mo
...
/usr/local/share/locale/fi/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/fr/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/es/LC_MESSAGES/exiv2.mo
852 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

So, your python test code should:
1. Skip the test on Windows (msvc, mingw, cygwin)
2. Search /usr/local/share/locale for the files exiv2.mo
Skip the test if doesn't find any
3. create the symbolic link
4. Popen ('bin/exiv2', ENV: LANG='fr_FR')   # LANGUAGE on Linux

**Comment by clanmills** [comment]
I've had more thoughts about this.

1. Localisation
I'm going to develop a bash test to do this and submit it to 0.27-maintenance.  When that's been done, you can add something to tests/bash_tests/testcases.py in a new PR.

2. stdin-test.sh is not being run on 0.27-maintenance.

3. Finishing #1301
I will integrate #1301 into 0.27-maintenance and fix it.  I don't believe stdin_test and icc_test are working correctly.  There might be missing tests.  I don't know.

4. Removing bash/make from the test suite is not started.  #1274

I'm not making progress with my book because:
1. Reviewing the rewrite of bash-tests in python is taking too much of my time.
2. Arnold is reporting bugs in the book's tvisitor.cpp code concerning Visual Studio.
3. Other exiv2 project matters: ISOBMFF, charsets, porting 'master' modernisation to 0.27-maintenance, bigtiff, ARM support .... and on and on and on.

The aim of the book is to enable me to retire.  It has doubled my work-load.

**Comment by clanmills** [comment]
I'm unable to get localisation to work from a script.  Here's what I've written:

```bash
#!/usr/bin/env bash
# Test driver for exiv2.exe nls support

source ./functions.source

(   cd "$testdir"
    nls=$(runTest exiv2 -vVg nls|tail -1)
    platform=$(runTest exiv2 -vVg platform|tail -1)
    if [ "$nls" != "enable_nls=1" ]; then
    	echo "exiv2 not bulid with nls"
    	exit 0
    fi
    if [ "$platform" == "platform=windows" ]; then
    	echo "nls_test cannot be run msvc builds" >2
    	exit 0
    fi
    if [ "$platform"  == "platform=linux" ]; then
    	LANG=LANGUAGE
    else 
    	LANG=LANG
    fi
    ##
    # if necessary ditto /usr/local/share/locale -> build/share/locale
    share=${bin}../share
    if [ ! -e $share ]; then
    	mkdir -p $share
    fi
    usr=/usr/local/share/locale
    if [ -e "$usr" -a -e "$share" ]; then
    	cp -r "$usr" "$share"
    else 
    	echo "localisation files are not installed in $usr"
    	exit 0
    fi
    ##
    # test a couple of languages
    for language in fr_FR es_ES; do 
        env $LANG=$language ${bin}exiv2 || true
    done

) 3>&1 > $results 2>&1

reportTest

# That's all Folks!
##
```

It still speaks english!    When I run bin/exiv2 from the command-line, it works:

```bash
env LANG=fr_FR bin/exiv2
exiv2: Une action doit être spécifié
exiv2: Au moins un fichier est nécessaire
Utilisation : exiv2  [ options ] [ action ] fichier ...

Manipulation des métadonnées EXIF issues des images.
869 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

When I run it from a tiny script, it works:

```bash
869 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ cat foo.sh 
#!/usr/bin/env bash

env LANG=fr_FR bin/exiv2
```

And that works:
```bash
870 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ ./foo.sh 
exiv2: Une action doit être spécifié
exiv2: Au moins un fichier est nécessaire
Utilisation : exiv2  [ options ] [ action ] fichier ...

Manipulation des métadonnées EXIF issues des images.
871 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I doesn't work from the script above.

I don't have any more time available to work on this.

**Comment by clanmills** [comment]
I'm opening this and will try again to get my script to work.

**Comment by clanmills** [comment]
PR #1341 Using `LC_ALL=fr_FR LANG=fr_FR ${bin}/exiv2` works from script.

**Comment by LeoHsiao1** [comment]
I find PR #1341 has not merged yet, I will wait for it to merge and then try to test it.

**Comment by clanmills** [comment]
Good to hear from you, @LeoHsiao1.  Can you add your message to #1341 and ask @piponazo to review and merge?

I've also  submitted a new bash_script test/png-test.sh in #1351.  Although I updated tests/bash_tests/testcases.py, png_test() isn't working quite correctly.  I would appreciate your help to fix that.

**Comment by piponazo** [comment]
I already reviewed and approved #1341 and it looks good to me. Since that PR is pointing to 0.27-maintenance I left the merge operation to you @clanmills , since you have a better overview of the changes being done in that branch.

**Comment by clanmills** [comment]
Thanks @piponazo. 

@LeoHsiao1 can you update #1341 by adding test_nls() to tests/bash_tests/testcases.py, please.  Thank You.

**Comment by LeoHsiao1** [comment]
Unfortunately, I pulled `fix_1278_nls_test_0.27` branch and compiled exiv2, but it still displayed in English:
```sh
leo@Leo:/mnt/d/1/exiv2/build$ git log | head -n 5
commit e103fb846439d943c60672efad9f78cfe9bd6c50
Author: clanmills <robin@clanmills.com>
Date:   Fri Oct 2 18:37:36 2020 +0100

    Makefile updated to run nls-test.sh as part of bash_tests
```
```sh
leo@Leo:/mnt/d/1/exiv2/build$ cmake .. -DEXIV2_ENABLE_NLS=1
...
leo@Leo:/mnt/d/1/exiv2/build$ make
...
leo@Leo:/mnt/d/1/exiv2/build$ bin/exiv2 -vVg nls
exiv2 0.27.3
enable_nls=1
leo@Leo:/mnt/d/1/exiv2/build$ env LANG=fr_FR bin/exiv2
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
```

**Comment by clanmills** [comment]
Thanks for investigating.

Can you do a `$ sudo make install` and run the test again?  The test copies the translation files from /usr/local/share/locale/../*.gmo files to build/share.  I thought I had something in the test to complain if it can't find the translation files.

**Comment by LeoHsiao1** [comment]
It still doesn't work:
```sh
leo@Leo:/mnt/d/1/exiv2/build$ sudo make install
...
-- Installing: /usr/local/bin/geotag
-- Set runtime path of "/usr/local/bin/geotag" to "$ORIGIN/../lib"
-- Installing: /usr/local/share/locale/bs/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/de/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/ca/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/es/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/fi/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/fr/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/gl/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/ms/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/nl/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/pl/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/pt/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/ru/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/sk/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/sv/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/ug/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/uk/LC_MESSAGES/exiv2.mo
-- Installing: /usr/local/share/locale/vi/LC_MESSAGES/exiv2.mo
leo@Leo:/mnt/d/1/exiv2/build$ bin/exiv2 -vVg nls
exiv2 0.27.3
enable_nls=1
leo@Leo:/mnt/d/1/exiv2/build$ env LANG=fr_FR bin/exiv2
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
```

**Comment by clanmills** [comment]
Here are some things to try:

1) env LC_ALL=fr_FR LANG=fr_FR exiv2     (exiv2  NOT bin/exiv2)
2) Make sure the translation files are installed:
```
2337 rmills@rmillsmbp:/usr/local/share $ finder exiv2.mo
./locale/sk/LC_MESSAGES/exiv2.mo
./locale/ug/LC_MESSAGES/exiv2.mo
./locale/pl/LC_MESSAGES/exiv2.mo
./locale/vi/LC_MESSAGES/exiv2.mo
./locale/sv/LC_MESSAGES/exiv2.mo
./locale/ms/LC_MESSAGES/exiv2.mo
./locale/ca/LC_MESSAGES/exiv2.mo
./locale/ru/LC_MESSAGES/exiv2.mo
./locale/pt/LC_MESSAGES/exiv2.mo
./locale/uk/LC_MESSAGES/exiv2.mo
./locale/bs/LC_MESSAGES/exiv2.mo
./locale/gl/LC_MESSAGES/exiv2.mo
./locale/nl/LC_MESSAGES/exiv2.mo
./locale/de/LC_MESSAGES/exiv2.mo
./locale/fi/LC_MESSAGES/exiv2.mo
./locale/fr/LC_MESSAGES/exiv2.mo
./locale/es/LC_MESSAGES/exiv2.mo
2338 rmills@rmillsmbp:/usr/local/share $ 
```
3 Make sure libintl is in memory:
```
2340 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiv2 -vVg lib | grep int
library=/usr/local/lib/libintl.8.dylib
```

If it's working from the command-line, try my script in your build directory:
```
$ cd build
$ (cd ../test ; ./nls-test.sh)
```

**Comment by LeoHsiao1** [comment]
I repeated the test on a new VPS. It seems that libintl is missing:
```sh
[root@vultrguest build]# env LC_ALL=fr_FR LANG=fr_FR exiv2
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
[root@vultrguest build]# exiv2 -vVg lib | grep int              
have_libintl=0
[root@vultrguest build]# cat /etc/centos-release   
CentOS Linux release 8.2.2004 (Core) 
[root@vultrguest build]# yum install gettext 
Last metadata expiration check: 0:12:20 ago on Sun 11 Oct 2020 10:34:17 PM CST.
Package gettext-0.19.8.1-17.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@vultrguest build]# locate libintl
/usr/include/libintl.h
/usr/share/awk/libintl.awk
[root@vultrguest build]# find /usr/local/share/ -name 'exiv2.mo'
/usr/local/share/locale/ms/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/fi/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/de/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/pt/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/sk/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/nl/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/bs/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/sv/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/gl/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/uk/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/ug/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/ca/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/vi/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/fr/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/ru/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/es/LC_MESSAGES/exiv2.mo
/usr/local/share/locale/pl/LC_MESSAGES/exiv2.mo
```

**Comment by clanmills** [comment]
You go to bed.  We'll deal with this during the week.  I'll built/test it this evening on Ubuntu.  I'll install a CentOS VM on the MacMini.

**Comment by clanmills** [comment]
I've got this build and working on centOS/7.  There's a bug in src/CMakeLists.txt.  I should not set:
```
set_source_files_properties(http.cpp PROPERTIES COMPILE_FLAGS -fno-sanitize=address,undefined)
```

I think this mistake arrived in the code when I was working on an ASAN issue with http.cpp.  I didn't realise I had submitted that into the codebase.  The fix is in branch fix_1278_nls_test_0.27.  Please work in that branch.  See #1341

```
[rmills@rmillsmm-centos build]$ git status
# On branch fix_1278_nls_test_0.27
nothing to commit, working directory clean
[rmills@rmillsmm-centos build]$ uname -a
Linux rmillsmm-centos 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[rmills@rmillsmm-centos build]$ env LANG=fr_FR exiv2
exiv2: Une action doit �tre sp�cifi�
exiv2: Au moins un fichier est n�cessaire
Utilisation : exiv2  [ options ] [ action ] fichier ...

Manipulation des m�tadonn�es EXIF issues des images.
[rmills@rmillsmm-centos build]$ 
```

My script fails and I think it has something to do with the terminal's character set handling.  

```bash
[rmills@rmillsmm-centos build]$ (cd ../test ; ./nls-test.sh)
1,2c1,2
< exiv2: Une action doit �tre sp�cifi�
< exiv2: Au moins un fichier est n�cessaire
---
> exiv2: Une action doit être spécifié
> exiv2: Au moins un fichier est nécessaire
5,6c5,6
< Manipulation des m�tadonn�es EXIF issues des images.
< exiv2: Se debe especificar una acci�n
---
> Manipulation des métadonnées EXIF issues des images.
> exiv2: Se debe especificar una acción
8c8
< Uso: exiv2 [ opciones ] [ acci�n ] archivo ...
---
> Uso: exiv2 [ opciones ] [ acción ] archivo ...
10c10
< manipular los metadatos Exif de las im�genes.
---
> manipular los metadatos Exif de las imágenes.
[rmills@rmillsmm-centos build]$ 
```

The CI is crazy.  I don't know why.  He's failing in `$ make bash_tests` iotest.sh complaining about the web-server.  However, it runs OK in the terminal.  I'll disable centOS on gitLab-ci again. 

Now then, young Leo @LeoHsiao1.  Your challenge is to get this all to work on your machine (in branch fix_1278_nls_test_0.27) and update tests/bash_tests/testcases.py with a new function nls-test().  I think you will not experience the terminal issue as python does the UTF-8 encoding.

```bash
[rmills@rmillsmm-centos build]$ make tests
[ 14%] Built target exiv2lib_int
[ 25%] Built target exiv2-xmp
[ 48%] Built target exiv2lib
[ 50%] Built target taglist
[ 52%] Built target exiv2
[ 53%] Built target conntest
[ 54%] Built target geotag
[ 56%] Built target exiv2json
[ 58%] Built target xmpsample
[ 61%] Built target metacopy
[ 62%] Built target xmpprint
[ 63%] Built target xmpparser-test
[ 64%] Built target xmpparse
[ 65%] Built target write2-test
[ 66%] Built target write-test
[ 68%] Built target exifvalue
[ 70%] Built target ini-test
[ 71%] Built target xmpdump
[ 72%] Built target werror-test
[ 74%] Built target path-test
[ 75%] Built target exifdata-test
[ 76%] Built target addmoddel
[ 77%] Built target iptcprint
[ 78%] Built target exifprint
[ 80%] Built target convert-test
[ 81%] Built target exifcomment
[ 82%] Built target iptceasy
[ 83%] Built target remotetest
[ 85%] Built target iptctest
[ 86%] Built target easyaccess-test
[ 87%] Built target key-test
[ 88%] Built target iotest
[ 90%] Built target largeiptc-test
[ 91%] Built target tiff-test
[ 92%] Built target mmap-test
[ 94%] Built target prevtest
[ 96%] Built target getopt-test
[ 97%] Built target exifdata
[ 98%] Built target mrwthumb
[100%] Built target stringto-test
Scanning dependencies of target tests

---- Running bash_tests ----

Running addmoddel.sh ...
all testcases passed.
Running conversions.sh ...
all testcases passed.
Running crw-test.sh ...
all testcases passed.
Running exifdata-test.sh ...
all testcases passed.
Running exiv2-test.sh ...
all testcases passed.
Running geotag-test.sh ...
all testcases passed.
Running icc-test.sh ...
ICC jpg md5 webp md5 png md5 jpg md5 jp2 md5 all testcases passed.
Running imagetest.sh ...

Erase all tests..................
Copy all tests.........
Copy iptc tests.........
---------------------------------------------------------
All test cases passed
Running iotest.sh ...

file io tests
---------------------------------------------------------
All test cases passed
Serving HTTP on 0.0.0.0 port 12760 (http://0.0.0.0:12760/) ...
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET / HTTP/1.1" 200 -
http://localhost:12760 status = 200
*** HTTP tests begin
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "HEAD /data/table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:02] "GET /data/table.jpg HTTP/1.0" 200 -
*** HTTP tests end
all testcases passed.
kill exiv2_httpServer 3319
Running iptctest.sh ...

Read tests..................
Remove tests..................
Add/Mod tests..................
Extended tests..................
---------------------------------------------------------
All test cases passed
Running iso65k-test.sh ...
all testcases passed.
Running nls-test.sh ...
1,2c1,2
< exiv2: Une action doit ętre spécifié
< exiv2: Au moins un fichier est nécessaire
---
> exiv2: Une action doit ĂŞtre spĂŠcifiĂŠ
> exiv2: Au moins un fichier est nĂŠcessaire
5,6c5,6
< Manipulation des métadonnées EXIF issues des images.
< exiv2: Se debe especificar una acción
---
> Manipulation des mĂŠtadonnĂŠes EXIF issues des images.
> exiv2: Se debe especificar una acciĂłn
8c8
< Uso: exiv2 [ opciones ] [ acción ] archivo ...
---
> Uso: exiv2 [ opciones ] [ acciĂłn ] archivo ...
10c10
< manipular los metadatos Exif de las imágenes.
---
> manipular los metadatos Exif de las imĂĄgenes.
Running modify-test.sh ...
all testcases passed.
Running path-test.sh ...
Running preview-test.sh ...
.....................................
all testcases passed.
Running stdin-test.sh ...
stdin XMP a (exiv2, xmp, iptc) ICC 
all testcases passed.
Running stringto-test.sh ...
all testcases passed.
Running tiff-test.sh ...
all testcases passed.
Running webp-test.sh ...
WebP delete insert ICC XMP EXIF all testcases passed.
Running write-test.sh ...
all testcases passed.
Running write2-test.sh ...
all testcases passed.
Running xmpparser-test.sh ...
all testcases passed.

---- Running python_tests ----

bash -c  . functions.source ; cd ../tests ; if [ ! -z $VERBOSE ]; then verbose=--verbose ;fi ; python3 runner.py $verbose 
........Serving HTTP on 127.0.0.1 port 12760 (http://127.0.0.1:12760/) ...
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [11/Oct/2020 21:03:17] "GET /table.jpg HTTP/1.0" 200 -
..................................................s...............s............ss............s....................................s...................................................s..........
----------------------------------------------------------------------
Ran 201 tests in 14.987s

OK (skipped=7)

---- Running version_test ----

exiv2 0.27.3
exiv2=0.27.3
platform=linux
compiler=G++
bits=64
dll=1
debug=1
cplusplus=199711
version=4.8.5 20150623 (Red Hat 4.8.5-39)
date=Oct 11 2020
time=20:53:48
processpath=/home/rmills/gnu/github/exiv2/fix_1278/build/bin
localedir=../share/locale
package_name=exiv2
curl=0
executable=/home/rmills/gnu/github/exiv2/fix_1278/build/bin/exiv2
library=/usr/lib64/libpthread-2.17.so
library=/usr/lib64/libexpat.so.1.6.0
library=/usr/lib64/libz.so.1.2.7
library=/usr/lib64/libc-2.17.so
library=/usr/lib64/libgcc_s-4.8.5-20150702.so.1
library=/usr/lib64/libm-2.17.so
library=/usr/lib64/libstdc++.so.6.0.19
library=/home/rmills/gnu/github/exiv2/fix_1278/build/lib/libexiv2.so.0.27.3
library=/usr/lib64/ld-2.17.so
have_strerror_r=1
have_inttypes=0
have_libintl=0
have_lensdata=1
have_iconv=1
have_memory=1
have_lstat=0
have_regex=0
have_regex_h=1
have_stdbool=1
have_stdint=1
have_stdlib=0
have_strlib=0
have_strerror_r=1
have_strings_h=0
have_mmap=1
have_munmap=1
have_sys_stat=1
have_unistd_h=0
have_sys_mman=1
have_libz=1
have_xmptoolkit=1
adobe_xmpsdk=0
have_bool=0
have_strings=1
have_sys_types=1
have_unistd=1
have_unicode_path=0
enable_video=0
enable_webready=0
enable_nls=1
use_curl=0
use_ssh=0
config_path=/home/rmills/.exiv2
uid=1000
euid=1000
gid=1000
xmlns entry count: 68
[100%] Built target tests
[rmills@rmillsmm-centos build]$ 
```

**Comment by clanmills** [comment]
I've merged #1341 into 0.27-maintenance and manually tested on my centOS VM.   Localisation works on my centOS VM.

The els-tests (both test/nls-test.sh) and test/bash_tests/testcases.py `nls-test()` are not working correctly on centOS .  I think we're going to have to "skip" nls_test on that platform.

1 test/nls-test.sh differs

The localisation is working.  The terminal output on centOS is different from the reference output.

```bash
[rmills@rmillsmm-centos build]$ (cd ../test ; ./nls-test.sh)
1,2c1,2
< exiv2: Une action doit �tre sp�cifi�
< exiv2: Au moins un fichier est n�cessaire
---
> exiv2: Une action doit être spécifié
> exiv2: Au moins un fichier est nécessaire
5,6c5,6
< Manipulation des m�tadonn�es EXIF issues des images.
< exiv2: Se debe especificar una acci�n
---
> Manipulation des métadonnées EXIF issues des images.
> exiv2: Se debe especificar una acción
8c8
< Uso: exiv2 [ opciones ] [ acci�n ] archivo ...
---
> Uso: exiv2 [ opciones ] [ acción ] archivo ...
10c10
< manipular los metadatos Exif de las im�genes.
---
> manipular los metadatos Exif de las imágenes.
```

2.  `$ make python_tests VERBOSE=1` is crashing and not storing its output file.

```bash
[rmills@rmillsmm-centos build]$ make python-tests
make: *** No rule to make target `python-tests'.  Stop.
[rmills@rmillsmm-centos build]$ make python_tests

---- Running python_tests ----

bash -c  . functions.source ; cd ../tests ; if [ ! -z $VERBOSE ]; then verbose=--verbose ;fi ; python3 runner.py $verbose 
...
======================================================================
ERROR: nls_test (bash_tests.testcases.TestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rmills/gnu/github/exiv2/0.27-maintenance/tests/bash_tests/testcases.py", line 894, in nls_test
    out += BT.Executer('exiv2', extra_env={'LC_ALL': language, LANG: language}, assert_returncode=[1])
  File "/home/rmills/gnu/github/exiv2/0.27-maintenance/tests/bash_tests/utils.py", line 453, in __init__
    self.run()
  File "/home/rmills/gnu/github/exiv2/0.27-maintenance/tests/bash_tests/utils.py", line 482, in run
    output      = [i.decode(self.encoding)      for i in output]
  File "/home/rmills/gnu/github/exiv2/0.27-maintenance/tests/bash_tests/utils.py", line 482, in <listcomp>
    output      = [i.decode(self.encoding)      for i in output]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 23: invalid continuation byte

----------------------------------------------------------------------
Ran 203 tests in 14.476s
```

So the file test/tmp/nls-test.out is not stored.  The message `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 23` indicates that there a Unicode marker `0xea` in the output and python `encoding` hates this.  I've seen this elsewhere (in png-test.out).

I think the best remedial course here is to skip nls_test on centOS.  In bash, we can detect we are in centos with:

```bash
if [ $uname == Linux ]; then 
  if [ $(cat /etc/os-release | grep ^ID= | cut -D'"' -f 2) == centos  ]; then
    echo "skip platform centos"
  fi
fi
```

In python:
```python
import platform
platform.dist()[0]=='centos'
```

**Comment by clanmills** [comment]
Here's another simple _(and better)_ idea.

Use `head` to limit the output from `$ env LANG=fr_FR exiv2 | head -c 20` to the first 20 bytes.  That's sufficient to know verify localisation _**and**_ avoid the UTF-8 complication.

```bash
597 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ for lang in fr_FR es_ES; do (env LANG=$lang exiv2 2>&1|head -c 20); echo ; done
exiv2: Une action do
exiv2: Se debe espec
598 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I believe this will pass on centos, MinGW/msys2 and cygwin64 and avoid "skipping" platforms.

Of course @LeoHsiao1 will have to something in python equivalent of `head -c 20`.  You'll fix this @LeoHsiao1, right?  Very pleased with your contributions.  Open-source is harder than you expected, right?   @piponazo and I are delighted that you are contributing.

**Comment by clanmills** [comment]
Beaten to death.  Let's move onto the next challenge. #1372

After that we have to "retire the old bash scripts" #1274 and then ............... we're done on #1215

(I'll probably think of something else before we close #1215 - however we're close to finishing this.  Great Job, Mr Lion).
