### ISSUE TITLE
exiv2 asserts on malicious file

### ISSUE THREAD

**Issue by NigelX** [Exiv2/exiv2#1558]
Hello exiv2 team
I found a crash on exiv2

Fedora 33
```bash
exiv2 -c txt  exiv2_crash
```
[exiv2_crash.zip](https://github.com/Exiv2/exiv2/files/6316567/exiv2_crash.zip)

<img width="791" alt="截屏2021-04-13 下午3 58 42" src="https://user-images.githubusercontent.com/25973989/114842558-88b00d00-9e0b-11eb-9a8b-8470a1713a60.png">

------------------------------------------------------------------------
## Affected Product Code Base
exiv2 1.0.0.9  commit：6cb34028c7f91b273e98b0ca789d677028afe4b9 

------------------------------------------------------------------------
## Affected source code file
affected source code file(As call stack):

-> main    				 					/exiv2/src/exiv2.cpp:167

-> Action::Modify::run  		 					/exiv2/src/actions.cpp:1324

 -> Exiv2::JpegBase::writeMetadata				/exiv2/src/jpgimage.cpp:908
	
  -> Exiv2::JpegBase::doWriteMetadata				/exiv2/src/jpgimage.cpp:1100

   		…

  -> Exiv2::Internal::TiffMnEntry::doCount.  			/exiv2/src/tiffcomposite_int.cpp:1030

------------------------------------------------------------------------
## Details 
```bash
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6d16859 in __GI_abort () at abort.c:79
#2  0x00007ffff6d16729 in __assert_fail_base (fmt=0x7ffff6eac588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
   assertion=0x7ffff7b23a60 <str> "tiffType() == ttUndefined || tiffType() == ttUnsignedByte || tiffType() == ttSignedByte", 
   file=0x7ffff7b228c0 <str> "/home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp", line=1030, function=<optimized out>) at assert.c:92
#3  0x00007ffff6d27f36 in __GI___assert_fail (
   assertion=0x7ffff7b23a60 <str> "tiffType() == ttUndefined || tiffType() == ttUnsignedByte || tiffType() == ttSignedByte", 
   file=0x7ffff7b228c0 <str> "/home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp", line=1030, 
   function=0x7ffff7b23ae0 <__PRETTY_FUNCTION__._ZNK5Exiv28Internal11TiffMnEntry7doCountEv> "virtual uint32_t Exiv2::Internal::TiffMnEntry::doCount() const") at assert.c:101
#4  0x00007ffff789fe94 in Exiv2::Internal::TiffMnEntry::doCount (this=<optimized out>)
   at /home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp:1030
#5  0x00007ffff78d0f7c in Exiv2::Internal::TiffEncoder::updateDirEntry (this=<optimized out>, buf=0x624000008284 "|\222\a\030X\002", 
   byteOrder=Exiv2::littleEndian, pTiffComponent=<optimized out>) at /home/hh/Downloads/exiv2/src/tiffvisitor_int.cpp:770
#6  0x00007ffff78d0e2f in Exiv2::Internal::TiffEncoder::visitDirectoryNext (this=<optimized out>, object=<optimized out>)
   at /home/hh/Downloads/exiv2/src/tiffvisitor_int.cpp:757
#7  0x00007ffff789f02a in Exiv2::Internal::TiffDirectory::doAccept (this=0x606000006380, visitor=...)
   at /home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp:915
#8  0x00007ffff789f2c3 in Exiv2::Internal::TiffComponent::accept (this=0x606000006380, visitor=...)
   at /home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp:885
#9  Exiv2::Internal::TiffSubIfd::doAccept (this=<optimized out>, visitor=...) at /home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp:925
#10 0x00007ffff789ef62 in Exiv2::Internal::TiffComponent::accept (this=0x60800000f220, visitor=...)
   at /home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp:885
#11 Exiv2::Internal::TiffDirectory::doAccept (this=0x606000005c60, visitor=...) at /home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp:913
#12 0x00007ffff78bce50 in Exiv2::Internal::TiffParserWorker::encode (io=..., pData=<optimized out>, size=<optimized out>, exifData=..., 
   iptcData=..., xmpData=..., root=<optimized out>, findEncoderFct=<optimized out>, pHeader=<optimized out>, pOffsetWriter=<optimized out>)
   at /home/hh/Downloads/exiv2/src/tiffimage_int.cpp:1783
#13 0x00007ffff76079f7 in Exiv2::ExifParser::encode (blob=..., pData=<optimized out>, size=<optimized out>, byteOrder=<optimized out>, 
   exifData=...) at /home/hh/Downloads/exiv2/src/exif.cpp:730
#14 0x00007ffff768fa9b in Exiv2::JpegBase::doWriteMetadata (this=0x612000000040, outIo=...)
   at /home/hh/Downloads/exiv2/src/jpgimage.cpp:1100
#15 0x00007ffff768ceaa in Exiv2::JpegBase::writeMetadata (this=0x612000000040) at /home/hh/Downloads/exiv2/src/jpgimage.cpp:908
#16 0x000000000052e315 in Action::Modify::run (this=<optimized out>, path="txt_crash/id:000000,sig:06,src:000042,time:647963,op:havoc,rep:16")
   at /home/hh/Downloads/exiv2/src/actions.cpp:1324
#17 0x00000000004cd4c0 in main (argc=<optimized out>, argv=<optimized out>) at /home/hh/Downloads/exiv2/src/exiv2.cpp:167
```
Thank !

**Comment by clanmills** [comment]
Thanks for report this.  I've reproduced your report with Exiv2 v0.27.4 RC2.

```bash
771 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 -c txt ~/Downloads/exiv2_crash 
Warning: Directory Photo, entry 0x927c has unknown Exif (TIFF) type 6151; setting type size 1.
Warning: Directory NikonPreview has an unexpected next pointer; ignored.
Warning: Directory Photo, entry 0x927c has unknown Exif (TIFF) type 6151; setting type size 1.
Warning: Directory NikonPreview has an unexpected next pointer; ignored.
Assertion failed: (tiffType() == ttUndefined || tiffType() == ttUnsignedByte || tiffType() == ttSignedByte), function doCount, file /Users/rmills/gnu/github/exiv2/0.27-maintenance/src/tiffcomposite_int.cpp, line 1030.
Abort trap: 6
772 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

Is this a crash?  It's an assert.  The file violates the Tiff specification by using a type of  6151.  (valid types are <=13 for Tiff).

I have written a metadata parser called tvisitor to illustrate my book **Image Metadata _and_ Exiv2 Architecture**.  https://clanmills.com/exiv2/book/  The tvisitor program also diagnoses the same issue with your file.

```cpp
765 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ ls -l ~/Downloads/exiv2_crash 
-rw-------@ 1 rmills  staff  87846 13 Apr 15:55 /Users/rmills/Downloads/exiv2_crash
766 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ tvisitor  -pRU ~/Downloads/exiv2_crash 
STRUCTURE OF JPEG FILE (II): /Users/rmills/Downloads/exiv2_crash
 address | marker       |  length | signature
       0 | 0xffd8 SOI  
       2 | 0xffe0 APP0  |      16 | JFIF_....1.1__..
      20 | 0xffe1 APP1  |    7815 | Exif__II*_.___._..._.___.___..._.___.___
  STRUCTURE OF TIFF FILE (II): /Users/rmills/Downloads/exiv2_crash:30->7807
   address |    tag                                  |      type |    count |    offset | value
        10 | 0x010e Exif.Image.ImageDescription      |     ASCII |       11 |       146 |           
        22 | 0x010f Exif.Image.Make                  |     ASCII |        6 |       158 | NIKON
        34 | 0x0110 Exif.Image.Model                 |     ASCII |        6 |       164 | E8800
        46 | 0x0112 Exif.Image.Orientation           |     SHORT |        1 |           | 1
        58 | 0x011a Exif.Image.XResolution           |  RATIONAL |        1 |       170 | 305/1
        70 | 0x011b Exif.Image.YResolution           |  RATIONAL |        1 |       178 | 305/1
        82 | 0x0128 Exif.Image.ResolutionUnit        |     SHORT |        1 |           | 2
        94 | 0x0131 Exif.Image.Software              |     ASCII |       12 |       186 | GIMP 2.6.10
       106 | 0x0132 Exif.Image.DateTime              |     ASCII |       20 |       198 | 2011:06:15 12:37:25
       118 | 0x0213 Exif.Image.YCbCrPositioning      |     SHORT |        1 |           | 1
       130 | 0x8769 Exif.Image.ExifTag               |      LONG |        1 |           | 218
    STRUCTURE OF TIFF FILE (II): /Users/rmills/Downloads/exiv2_crash:30->7807
     address |    tag                                  |      type |    count |    offset | value
         220 | 0x829a Exif.Photo.ExposureTime          |  RATIONAL |        1 |       488 | 330469/100000000
         232 | 0x829d Exif.Photo.FNumber               |  RATIONAL |        1 |       496 | 73/10
         244 | 0x8822 Exif.Photo.ExposureProgram       |     SHORT |        1 |           | 2
         256 | 0x8827 Exif.Photo.ISOSpeedRatings       |     SHORT |        1 |           | 200
         268 | 0x9000 Exif.Photo.ExifVersion           | UNDEFINED |        4 |           | 0220
         280 | 0x9003 Exif.Photo.DateTimeOriginal      |     ASCII |       20 |       504 | 2004:11:17 10:24:16
         292 | 0x9004 Exif.Photo.DateTimeDigitized     |     ASCII |       20 |       524 | 2004:11:17 10:24:16
         304 | 0x9101 Exif.Photo.ComponentsConfigura.. | UNDEFINED |        4 |           | ..._
         316 | 0x9204 Exif.Photo.ExposureBiasValue     | SRATIONAL |        1 |       544 | 0/10
         328 | 0x9205 Exif.Photo.MaxApertureValue      |  RATIONAL |        1 |       552 | 31/10
         340 | 0x9207 Exif.Photo.MeteringMode          |     SHORT |        1 |           | 3
         352 | 0x9208 Exif.Photo.LightSource           |     SHORT |        1 |           | 0
         364 | 0x9209 Exif.Photo.Flash                 |     SHORT |        1 |           | 16
         376 | 0x920a Exif.Photo.FocalLength           |  RATIONAL |        1 |       560 | 49/1
invalid type 6151
767 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ 
``` 

I'm not sure of your expectations here.  Can you let me know what you want me to do about this?

I take security very seriously.  If it's really necessary to fix this for v0.27.4, I can change the behaviour of the assert to print a message and terminate the process.  I am hoping to promote Exiv2 v0.27.4 RC2 to GM and release it at the end of the April.  If are actively engaged in finding security issues in Exiv2, perhaps you could collect all your reports and they will be dealt with together.  Preferrably, after Exiv2 v0.27.4 GM has been released.

**Comment by NigelX** [comment]
hi clanmills 
I think it is better to change the assertion behavior so that it prints the message and terminates the process.

**Comment by clanmills** [comment]
I think you're using a debug build.  On the release build, I see:

```
789 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 -vVg debug -g exiv2
exiv2 0.27.4.2
exiv2=0.27.4
debug=0
package_name=exiv2
executable=/usr/local/bin/exiv2
library=/usr/local/lib/libexiv2.0.27.4.2.dylib
config_path=/Users/rmills/.exiv2
790 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 -c txt ~/Downloads/exiv2_crash 
Warning: Directory Photo, entry 0x927c has unknown Exif (TIFF) type 6151; setting type size 1.
Warning: Directory NikonPreview has an unexpected next pointer; ignored.
Warning: Directory Photo, entry 0x927c has unknown Exif (TIFF) type 6151; setting type size 1.
Warning: Directory NikonPreview has an unexpected next pointer; ignored.
791 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ echo $?
0
792 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

**Comment by NigelX** [comment]
I am using exiv2 installed with yum command on Fedora 33

**Comment by clanmills** [comment]
Can you run the command: `$ exiv2 -vVg debug -g exiv2` to report the version (1.0.0.9 for you, I believe.  That's correct for "head of branch".  That's a development branch.  I don't know yum/Fedora and surprised it installs development code.

If debug=1, then yum has install a debug version.  I see you have a functions traceback.  I think you only get that information with a debug build.

**Comment by clanmills** [comment]
I'm discussing this with Team Exiv2 on our chat server.  Apparently yum installs development branches.  That's unwise and unsafe.  Download the Linux build of Exiv2 v0.27.4 RC2 from https://pre-release.exiv2.org.  There's a file "ReadMe.txt" in bundle that explains how to install it.

**Comment by clanmills** [comment]
Chat Server: 
[![#exiv2-chat on matrix.org](https://user-images.githubusercontent.com/529982/106066609-0742bb80-60f5-11eb-8893-2989c854e20d.png)](https://matrix.to/#/#exiv2-chat:matrix.org)

**Comment by NigelX** [comment]
Source code 
```bash
topsec :: exiv2/build/bin ‹main› » ./exiv2 -c txt exiv2_crash
Warning: Directory Photo, entry 0x927c has unknown Exif (TIFF) type 6151; setting type size 1.
Warning: Directory NikonPreview has an unexpected next pointer; ignored.
Warning: Directory Photo, entry 0x927c has unknown Exif (TIFF) type 6151; setting type size 1.
Warning: Directory NikonPreview has an unexpected next pointer; ignored.
exiv2: /home/hh/Downloads/exiv2/src/tiffcomposite_int.cpp:1030: virtual uint32_t Exiv2::Internal::TiffMnEntry::doCount() const: Assertion `tiffType() == ttUndefined || tiffType() == ttUnsignedByte || tiffType() == ttSignedByte' failed.
[1]    2636359 abort      ./exiv2 -c txt exiv2_crash

topsec :: exiv2/build/bin ‹main› » ./exiv2 -vVg debug -g exiv2                                                     
exiv2 1.0.0.9
exiv2=1.0.0
debug=1
processpath=/home/hh/Downloads/exiv2/build/bin
package_name=exiv2
executable=/home/hh/Downloads/exiv2/build/bin/exiv2
library=/home/hh/Downloads/exiv2/build/lib/libexiv2.so.1.0.0.9
config_path=/home/hh/.exiv2
```

Fedora 33
```bash
[hh@localhost txt_crash]$ exiv2 -c txt id:000000,sig:06,src:000042,time:647963,op:havoc,rep:16
Warning: Directory Photo, entry 0x927c has unknown Exif (TIFF) type 6151; setting type size 1.
Warning: Directory NikonPreview has an unexpected next pointer; ignored.
Warning: Directory Photo, entry 0x927c has unknown Exif (TIFF) type 6151; setting type size 1.
Warning: Directory NikonPreview has an unexpected next pointer; ignored.
exiv2: /builddir/build/BUILD/exiv2-0.27.3-Source/src/tiffcomposite_int.cpp:1034: virtual uint32_t Exiv2::Internal::TiffMnEntry::doCount() const: Assertion `tiffType() == ttUndefined || tiffType() == ttUnsignedByte || tiffType() == ttSignedByte' failed.
Aborted (core dumped)

[hh@localhost txt_crash]$ exiv2 -vVg debug -g exiv2
exiv2 0.27.3
exiv2=0.27.3
debug=1
package_name=exiv2
executable=/usr/bin/exiv2
library=/usr/lib64/libexiv2.so.0.27.3
config_path=/home/hh/.exiv2
```

**Comment by clanmills** [comment]
@NigelX Can you join us on the Chatserver, please.  Let's all discuss this together.  Other team members know much more about Fedora than I know.

**Comment by kmilos** [comment]
@clanmills Fedora does not ship the development branch, 0.27.3 is the current version packaged . However, perhaps exiv2 shouldn't default to debug build if no CMake option is given: https://src.fedoraproject.org/rpms/exiv2/blob/rawhide/f/exiv2.spec#_84

**Comment by clanmills** [comment]
The Exiv2 document README.md claims it defaults to release.  
<img width="821" alt="screenshot_44" src="https://user-images.githubusercontent.com/529982/114857333-09f1aa80-9de0-11eb-9d10-1dc5f038e77d.png">

Exiv2 does rely on the default provided by CMake:

```bash
799 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ find . -name CMakeLists.txt | xargs grep CMAKE_BUILD_TYPE
800 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ find . -name "*.cmake" | xargs grep CMAKE_BUILD_TYPE
./cmake/compilerFlags.cmake:        if (CMAKE_BUILD_TYPE STREQUAL Release AND NOT (APPLE OR MINGW OR MSYS))
./cmake/compilerFlags.cmake:        if (CMAKE_BUILD_TYPE STREQUAL "Debug")
./cmake/packaging.cmake:if ( NOT ${CMAKE_BUILD_TYPE} STREQUAL Release )
./cmake/packaging.cmake:	set (BT ${CMAKE_BUILD_TYPE})
./cmake/printSummary.cmake:message( STATUS "CMAKE_BUILD_TYPE:  ${CMAKE_BUILD_TYPE}" )
801 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ 
```

I've regenerate the build and it reports:

```
-- CMAKE_BUILD_TYPE:  
```
So, it's _**undefined**_.  

Perhaps we should change _**undefined**_ to Release.

**Comment by kmilos** [comment]
I'm still trying to get how this "undefined" gets understood as Debug though...

**Comment by clanmills** [comment]
@NigelX I'm going to create a PR to `set (CMAKE_BUILD_TYPE Release)` in CMakeLists.txt.  This will bring the code and README.md into 100% agreement.  So yum will build you a release version in future.

Getting back to the security issue.  Do you agree that there is no case to answer?

**Comment by kmilos** [comment]
Reported to Fedora as well: https://bugzilla.redhat.com/show_bug.cgi?id=1949903

**Comment by clanmills** [comment]
Thanks for reporting that to Fedora, @kmilos.  

Patch (for 'main' v1.00 is)
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5434be5..7d8e43b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,6 +9,11 @@ project(exiv2          # use TWEAK to categorize the build
                        # 1.00.0.29 = RC2 Development
     LANGUAGES CXX
 )
+
+if(NOT CMAKE_BUILD_TYPE)
+    set (CMAKE_BUILD_TYPE Release)
+endif()
+
 include(cmake/mainSetup.cmake  REQUIRED)
 
 # options and their default values
```

@NigelX If you're happy with our explanation and action, I invite you to close this ticket.

**Comment by clanmills** [comment]
PR Submitted: #1559.

**Comment by kmilos** [comment]
> I'm still trying to get how this "undefined" gets understood as Debug though...

Ah, it's not necessarily a proper Debug build, but just that NDEBUG is not defined among some other things, so it's just reported as one:

https://github.com/Exiv2/exiv2/blob/52b2855c49679b179e324740af274daf12efa56c/src/version.cpp#L239

NDEBUG also affects the [assert](https://en.cppreference.com/w/c/error/assert).

**Comment by clanmills** [comment]
You are right.  We should report ndebug=1|0 because that's what we know.

The assert and traceback were in the user's report.  To make more progress with this, will probably involve forsensics such as shared object sizes for building/download Exiv2.  I don't want to spend an afternoon on this.  It's an assert being correctly called on a malicious file.

**Comment by kmilos** [comment]
> To make more progress with this, will probably involve forensics...

No need, I think it's safe to say with no build type specified (and no default provided), you get neither the `-g` switch of the Debug build, nor the `-O2 -DNDEBUG` of the Release one.
