### ISSUE TITLE
test_pr_1905.TestExifTagsInTaglist depends on cut command

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#2108]
##### **Describe the bug**
The test file `tests/bash_tests/test_pr_1905.py` depends on the `cut` command available on bash shells. Therefore, when one tries to run all the project tests with `ctest` on windows with CMD or PowerShell, that test fails:

````
1: ======================================================================
1: FAIL: test_run (test_pr_1905.TestExifTagsInTaglist)
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "F:\projects\exiv2\tests\system_tests.py", line 652, in test_run
1:     self.compare_stderr(i, command, processed_stderr, stderr)
1:   File "F:\projects\exiv2\tests\system_tests.py", line 773, in compare_stderr
1:     self._compare_output(
1:   File "F:\projects\exiv2\tests\system_tests.py", line 745, in _compare_output
1:     self.assertMultiLineEqual(
1: AssertionError: "'cut' is not recognized as an internal o[50 chars]e.\n" != ''
1: - 'cut' is not recognized as an internal or external command,
1: - operable program or batch file.
1:  : Standard error does not match
1:
1: ----------------------------------------------------------------------
1: Ran 33 tests in 11.707s
```
##### **To Reproduce**
Steps to reproduce the behavior:
1. Compile the projedt under windows
2. Run `ctest` on a CMD or Powershell. You should not have in your `PATH` any directory that might containg the cut command.

##### **Expected behavior**
All tests pass correctly.

##### **Desktop (please complete the following information):**
- OS and version: (Windows 11)
- Compiler and version: (MSVC 2022)
- Compilation mode and/or compiler flags: Release. No special flags.

##### **Additional context**
Even though the `windows-2022` github instances seems to use by default PowerShell, I guess that they include in their `PATH` the directories in which the bash terminals are installed. Therefore, the problem is not visible in our CI infrastructure.

**Comment by postscript-dev** [comment]
@piponazo :
Thanks for pointing this out. I created the original PR and will take a look at this tomorrow.
