### ISSUE TITLE
heap-buffer-overflow src/types.cpp:234 in Exiv2::getUShort(unsigned char const*, Exiv2::ByteOrder)

### ISSUE THREAD

**Issue by fgeek** [Exiv2/exiv2#211]
http://bugs.fi/media/afl/exiv2/2018-01-09-exiv2-crash-003.tiff
4be065595e4b81e876e32c9c4705f8313f896d43

```
=3015==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000d3d6 at pc 0x7f457e3fc981 bp 0x7ffc19b9b000 sp 0x7ffc19b9aff8
READ of size 1 at 0x60300000d3d6 thread T0
    #0 0x7f457e3fc980 in Exiv2::getUShort(unsigned char const*, Exiv2::ByteOrder) /home/hsalo/src/exiv2/src/types.cpp:234
    #1 0x7f457e14fbb2 in Exiv2::IptcData::printStructure(std::ostream&, unsigned char const*, unsigned long, unsigned int) /home/hsalo/src/exiv2/src/iptc.cpp:361
    #2 0x7f457e12d441 in Exiv2::Image::printIFDStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, unsigned int, bool, char, int) /home/hsalo/src/exiv2/src/image.cpp:470
    #3 0x7f457e12f602 in Exiv2::Image::printTiffStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, int, unsigned long) /home/hsalo/src/exiv2/src/image.cpp:533
    #4 0x7f457e3b9eeb in Exiv2::TiffImage::printStructure(std::ostream&, Exiv2::PrintStructureOption, int) /home/hsalo/src/exiv2/src/tiffimage.cpp:344
    #5 0x7f457e3b79c4 in Exiv2::TiffImage::readMetadata() /home/hsalo/src/exiv2/src/tiffimage.cpp:187
    #6 0x55cf127a7ad6 in Action::Print::printSummary() /home/hsalo/src/exiv2/src/actions.cpp:296
    #7 0x55cf127ac077 in Action::Print::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/hsalo/src/exiv2/src/actions.cpp:242
    #8 0x55cf1274287b in main /home/hsalo/src/exiv2/src/exiv2.cpp:166
    #9 0x7f457d1812b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #10 0x55cf12743729 in _start (/home/hsalo/builds/exiv2/2018-01-08/bin/exiv2+0x12729)

0x60300000d3d6 is located 0 bytes to the right of 22-byte region [0x60300000d3c0,0x60300000d3d6)
allocated by thread T0 here:
    #0 0x7f457f03cd70 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc2d70)
    #1 0x7f457e12d358 in Exiv2::Image::printIFDStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, unsigned int, bool, char, int) /home/hsalo/src/exiv2/src/image.cpp:467
    #2 0x7f457e12f602 in Exiv2::Image::printTiffStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, int, unsigned long) /home/hsalo/src/exiv2/src/image.cpp:533
    #3 0x7f457e3b9eeb in Exiv2::TiffImage::printStructure(std::ostream&, Exiv2::PrintStructureOption, int) /home/hsalo/src/exiv2/src/tiffimage.cpp:344
    #4 0x7f457e3b79c4 in Exiv2::TiffImage::readMetadata() /home/hsalo/src/exiv2/src/tiffimage.cpp:187
    #5 0x55cf127a7ad6 in Action::Print::printSummary() /home/hsalo/src/exiv2/src/actions.cpp:296
    #6 0x55cf127ac077 in Action::Print::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/hsalo/src/exiv2/src/actions.cpp:242
    #7 0x55cf1274287b in main /home/hsalo/src/exiv2/src/exiv2.cpp:166
    #8 0x7f457d1812b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/hsalo/src/exiv2/src/types.cpp:234 in Exiv2::getUShort(unsigned char const*, Exiv2::ByteOrder)
Shadow bytes around the buggy address:
  0x0c067fff9a20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9a30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9a40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9a50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9a60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c067fff9a70: fa fa fa fa fa fa fa fa 00 00[06]fa fa fa fd fd
  0x0c067fff9a80: fd fd fa fa fd fd fd fa fa fa fd fd fd fa fa fa
  0x0c067fff9a90: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x0c067fff9aa0: fa fa 00 00 00 07 fa fa 00 00 00 07 fa fa 00 00
  0x0c067fff9ab0: 00 07 fa fa 00 00 00 07 fa fa 00 00 00 07 fa fa
  0x0c067fff9ac0: 00 00 00 07 fa fa 00 00 00 07 fa fa 00 00 00 07
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3015==ABORTING
```

**Comment by piponazo** [comment]
Hi @fgeek. I just tried to reproduce your problem on the master branch and the application correctly reports  that the metadata is corrupted:

```
19:29 $ bin/exiv2 ~/2018-01-09-exiv2-crash-003.tiff 
Exiv2 exception in print action for file /home/luis/2018-01-09-exiv2-crash-003.tiff:
corrupted image metadata
```
Could you validate if you still have the problem?
