### ISSUE TITLE
x86 Tests Failing

### ISSUE THREAD

**Issue by neheb** [Exiv2/exiv2#2539]
#### **Describe the bug**
```
2: ======================================================================
2: FAIL: test_run (github.test_CVE_2017_11591.TestCvePoC)
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/exiv2/tests/system_tests.py", line 652, in test_run
2:     self.compare_stderr(i, command, processed_stderr, stderr)
2:   File "/exiv2/tests/system_tests.py", line 966, in check_no_ASAN_UBSAN_errors
2:     self.assertNotIn(UBSAN_MSG, got_stderr)
2: AssertionError: 'runtime error' unexpectedly found in 'Error: Directory Image, entry 0x0000 has invalid size 4286578688*8; skipping entry.\nWarning: Directory Image, entry 0x0111: Strip 0 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 1 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 2 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 3 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 4 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 5 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 7 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 8 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 10 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 12 is outside of the data area; ignored.\n/exiv2/src/tiffcomposite_int.cpp:298:45: runtime error: pointer index expression with base 0xf2135000 overflowed to 0x53135000\n'
2: 
2: ======================================================================
2: FAIL: test_run (github.test_CVE_2017_14859.TestCvePoC)
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/exiv2/tests/system_tests.py", line 652, in test_run
2:     self.compare_stderr(i, command, processed_stderr, stderr)
2:   File "/exiv2/tests/bugfixes/github/test_CVE_2017_14859.py", line 19, in compare_stderr
2:     self.assertIn(expected_stderr, got_stderr)
2: AssertionError: 'Exiv2 exception in print action for file /exiv2/test/data/005-invalid-mem:\ncorrupted image metadata\n' not found in 'Warning: Directory Image, entry 0x011a has unknown Exif (TIFF) type 64772; setting type size 1.\n/exiv2/src/tiffvisitor_int.cpp:1319:48: runtime error: pointer index expression with base 0xef802138 overflowed to 0x2f802140\n'
2: 
2: ----------------------------------------------------------------------
2: Ran 300 tests in 56.875s
2: 
2: FAILED (failures=2, skipped=10)

```
#### **To Reproduce**
Dockerfile:
```
FROM i386/debian

RUN apt update; apt install -y cmake g++ clang make libexpat1-dev zlib1g-dev libbrotli-dev libssh-dev libcurl4-openssl-dev libgtest-dev libxml2-utils libinih-dev python3-dev git gettext libgmock-dev libgtest-dev neovim vim nano && \
  git clone https://github.com/Exiv2/exiv2 && cd exiv2 && \
  cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DEXIV2_ENABLE_NLS=TRUE -DEXIV2_BUILD_SAMPLES=TRUE -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_ENABLE_VIDEO=ON -DEXIV2_BUILD_SAMPLES=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_TEAM_USE_SANITIZERS=ON -DEXIV2_TEAM_EXTRA_WARNINGS=ON && \
  cmake --build . --parallel && \
  ctest . -VV
```

```
docker build -t test-image -f Dockerfile
```

#### **Expected behavior**
Tests passing

ping @kevinbackhouse

**Comment by kevinbackhouse** [comment]
@neheb: I thought we had x86 tests running in our Actions workflows now? Is this a different configuration that you'd like to enable?

It might be easiest to just delete this test if it continues to cause problems. It's a regression test for an old bug that would get caught very quickly by OSS-Fuzz if it were accidentally reintroduced.

**Comment by neheb** [comment]
x86 under Windows. Note that I enable UBSAN here.

**Comment by neheb** [comment]
errors on arm32:

```
======================================================================
FAIL: test_run (github.test_CVE_2017_11591.TestCvePoC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 966, in check_no_ASAN_UBSAN_errors
    self.assertNotIn(UBSAN_MSG, got_stderr)
AssertionError: 'runtime error' unexpectedly found in 'Error: Directory Image, entry 0x0000 has invalid size 4286578688*8; skipping entry.\nWarning: Directory Image, entry 0x0111: Strip 0 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 1 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 2 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 3 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 4 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 5 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 7 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 8 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 10 is outside of the data area; ignored.\nWarning: Directory Image, entry 0x0111: Strip 12 is outside of the data area; ignored.\n/home/mangix/devstuff/exiv2/src/tiffcomposite_int.cpp:297:45: runtime error: pointer index expression with base 0xb1d51000 overflowed to 0x12d51000\n'

======================================================================
FAIL: test_run (github.test_CVE_2018_12265.AdditionOverflowInLoaderExifJpeg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Erro[319 chars]ata area; ignored.\n' != 'Erro[319 chars]ata area; ignored.\nUncaught exception: Overflow in addition\n'
  Error: Upper boundary of data for directory Image, entry 0x00fe is out of bounds: Offset = 0x0000002a, size = 64, exceeds buffer size by 22 Bytes; truncating the entry
  Warning: Directory Image, entry 0x0201: Strip 0 is outside of the data area; ignored.
  Warning: Directory Image, entry 0x0201: Strip 7 is outside of the data area; ignored.
+ Uncaught exception: Overflow in addition
 : Standard error does not match

======================================================================
FAIL: test_run (github.test_pr_2244.test_pr_2244)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Unca[35 chars] high=========================================[2458 chars]NG\n' != 'Unca[35 chars] high\n'
+ Uncaught exception: year adjustment too high
- Uncaught exception: year adjustment too high=================================================================
- ==28940==ERROR: AddressSanitizer: stack-use-after-scope on address 0xbebc5328 at pc 0xb69caadb bp 0xbebc4ee8 sp 0xbebc4ef0
- READ of size 256 at 0xbebc5328 thread T0
-     #0 0xb69caad8 in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806
-     #1 0xb449c770 in std::ctype<char>::_M_widen_init() const (/lib/arm-linux-gnueabihf/libstdc++.so.6+0x95770)
-     #2 0x58e1c4 in std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&) [clone .isra.0] (/home/mangix/devstuff/exiv2/bb/bin/exiv2+0x9e1c4)
-     #3 0x58c492 in main (/home/mangix/devstuff/exiv2/bb/bin/exiv2+0x9c492)
-     #4 0xb3dda59c in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x1759c)
-
- Address 0xbebc5328 is located in stack of thread T0
- SUMMARY: AddressSanitizer: stack-use-after-scope ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806 in __interceptor_memcpy
- Shadow bytes around the buggy address:
-   0x37d78a10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d78a20: 00 00 00 00 00 00 00 00 00 00 f8 00 00 00 00 00
-   0x37d78a30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d78a40: 00 00 f8 00 00 00 00 00 00 00 00 00 f8 00 00 00
-   0x37d78a50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
- =>0x37d78a60: 00 00 00 00 f8[f8]f8 00 00 00 00 00 00 00 00 00
-   0x37d78a70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d78a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d78a90: 00 00 00 00 00 00 00 00 00 00 00 00 f8 00 00 00
-   0x37d78aa0: f8 00 f8 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d78ab0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
- Shadow byte legend (one shadow byte represents 8 application bytes):
-   Addressable:           00
-   Partially addressable: 01 02 03 04 05 06 07
-   Heap left redzone:       fa
-   Freed heap region:       fd
-   Stack left redzone:      f1
-   Stack mid redzone:       f2
-   Stack right redzone:     f3
-   Stack after return:      f5
-   Stack use after scope:   f8
-   Global redzone:          f9
-   Global init order:       f6
-   Poisoned by user:        f7
-   Container overflow:      fc
-   Array cookie:            ac
-   Intra object redzone:    bb
-   ASan internal:           fe
-   Left alloca redzone:     ca
-   Right alloca redzone:    cb
-   Shadow gap:              cc
- ==28940==ABORTING
 : Standard error does not match

```

**Comment by neheb** [comment]
```
100% tests passed, 0 tests failed out of 7

Total Test time (real) = 142.95 sec
```

on that docker container.

```
======================================================================
FAIL: test_run (github.test_CVE_2018_12265.AdditionOverflowInLoaderExifJpeg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Erro[319 chars]ata area; ignored.\n' != 'Erro[319 chars]ata area; ignored.\nUncaught exception: Overflow in addition\n'
  Error: Upper boundary of data for directory Image, entry 0x00fe is out of bounds: Offset = 0x0000002a, size = 64, exceeds buffer size by 22 Bytes; truncating the entry
  Warning: Directory Image, entry 0x0201: Strip 0 is outside of the data area; ignored.
  Warning: Directory Image, entry 0x0201: Strip 7 is outside of the data area; ignored.
+ Uncaught exception: Overflow in addition
 : Standard error does not match

======================================================================
FAIL: test_run (github.test_pr_2244.test_pr_2244)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Unca[33 chars]o low=========================================[2458 chars]NG\n' != 'Unca[33 chars]o low\n'
+ Uncaught exception: day adjustment too low
- Uncaught exception: day adjustment too low=================================================================
- ==19475==ERROR: AddressSanitizer: stack-use-after-scope on address 0xbeceaca8 at pc 0xb6ab1adb bp 0xbecea868 sp 0xbecea870
- READ of size 256 at 0xbeceaca8 thread T0
-     #0 0xb6ab1ad8 in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806
-     #1 0xb458b770 in std::ctype<char>::_M_widen_init() const (/lib/arm-linux-gnueabihf/libstdc++.so.6+0x95770)
-     #2 0x56e1c4 in std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&) [clone .isra.0] (/home/mangix/devstuff/exiv2/bb/bin/exiv2+0x9e1c4)
-     #3 0x56c492 in main (/home/mangix/devstuff/exiv2/bb/bin/exiv2+0x9c492)
-     #4 0xb3ec959c in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x1759c)
- 
- Address 0xbeceaca8 is located in stack of thread T0
- SUMMARY: AddressSanitizer: stack-use-after-scope ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806 in __interceptor_memcpy
- Shadow bytes around the buggy address:
-   0x37d9d540: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d9d550: 00 00 00 00 00 00 00 00 00 00 f8 00 00 00 00 00
-   0x37d9d560: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d9d570: 00 00 f8 00 00 00 00 00 00 00 00 00 f8 00 00 00
-   0x37d9d580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
- =>0x37d9d590: 00 00 00 00 f8[f8]f8 00 00 00 00 00 00 00 00 00
-   0x37d9d5a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d9d5b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d9d5c0: 00 00 00 00 00 00 00 00 00 00 00 00 f8 00 00 00
-   0x37d9d5d0: f8 00 f8 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d9d5e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
- Shadow byte legend (one shadow byte represents 8 application bytes):
-   Addressable:           00
-   Partially addressable: 01 02 03 04 05 06 07 
-   Heap left redzone:       fa
-   Freed heap region:       fd
-   Stack left redzone:      f1
-   Stack mid redzone:       f2
-   Stack right redzone:     f3
-   Stack after return:      f5
-   Stack use after scope:   f8
-   Global redzone:          f9
-   Global init order:       f6
-   Poisoned by user:        f7
-   Container overflow:      fc
-   Array cookie:            ac
-   Intra object redzone:    bb
-   ASan internal:           fe
-   Left alloca redzone:     ca
-   Right alloca redzone:    cb
-   Shadow gap:              cc
- ==19475==ABORTING
 : Standard error does not match

----------------------------------------------------------------------
Ran 300 tests in 342.454s

FAILED (failures=2, skipped=10)

```

on arm32

**Comment by neheb** [comment]
```
======================================================================
FAIL: test_run (github.test_CVE_2018_12265.AdditionOverflowInLoaderExifJpeg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Erro[319 chars]ata area; ignored.\n' != 'Erro[319 chars]ata area; ignored.\nUncaught exception: Overflow in addition\n'
  Error: Upper boundary of data for directory Image, entry 0x00fe is out of bounds: Offset = 0x0000002a, size = 64, exceeds buffer size by 22 Bytes; truncating the entry
  Warning: Directory Image, entry 0x0201: Strip 0 is outside of the data area; ignored.
  Warning: Directory Image, entry 0x0201: Strip 7 is outside of the data area; ignored.
+ Uncaught exception: Overflow in addition
 : Standard error does not match

======================================================================
FAIL: test_run (github.test_issue_ghsa_jgm9_5fw5_pw9p.WebPImageDoWriteMetadataOutOfBoundsRead)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: "Warn[2155 chars]jp2: =========================================[2885 chars]NG\n" != "Warn[2155 chars]jp2: Could not write metadata to file: corrupt[15 chars]ta\n"
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x010f has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x010f has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x8769 has unknown Exif (TIFF) type 0; setting type size 1.
  Warning: Directory Image, entry 0x8769 doesn't look like a sub-IFD.
  Warning: Directory Image, entry 0x8825 doesn't look like a sub-IFD.
+ /home/mangix/devstuff/exiv2/test/data/issue_ghsa_jgm9_5fw5_pw9p_poc.jp2: Could not write metadata to file: corrupted image metadata
- /home/mangix/devstuff/exiv2/test/data/issue_ghsa_jgm9_5fw5_pw9p_poc.jp2: =================================================================
- ==30226==ERROR: AddressSanitizer: stack-use-after-scope on address 0xbecabb80 at pc 0xb6a2161b bp 0xbecab5e8 sp 0xbecab5f0
- WRITE of size 768 at 0xbecabb80 thread T0
-     #0 0xb6a21618 in __interceptor_memset ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:778
-     #1 0xb36e67f6 in std::filesystem::__cxx11::path::_M_split_cmpts() (/lib/arm-linux-gnueabihf/libstdc++.so.6+0xf77f6)
-     #2 0xb4978782 in std::filesystem::__cxx11::path::path<char [15], std::filesystem::__cxx11::path>(char const (&) [15], std::filesystem::__cxx11::path::format) /usr/include/c++/10/bits/fs_path.h:227
-     #3 0xb4977b06 in Exiv2::getProcessPath[abi:cxx11]() /home/mangix/devstuff/exiv2/src/futils.cpp:378
-     #4 0xb4b43d7a in _exvGettext(char const*) /home/mangix/devstuff/exiv2/src/types.cpp:648
-     #5 0x6a0ff8 in metacopy /home/mangix/devstuff/exiv2/app/actions.cpp:1791
-     #6 0x671d18 in Action::Insert::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/mangix/devstuff/exiv2/app/actions.cpp:979
-     #7 0x54fc1c in main /home/mangix/devstuff/exiv2/app/exiv2.cpp:176
-     #8 0xb2fc259c in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x1759c)
- 
- Address 0xbecabb80 is located in stack of thread T0
- SUMMARY: AddressSanitizer: stack-use-after-scope ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:778 in __interceptor_memset
- Shadow bytes around the buggy address:
-   0x37d95720: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d95730: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d95740: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d95750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d95760: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
- =>0x37d95770:[f8]f8 00 00 f8 f8 00 00 00 00 00 00 00 00 00 00
-   0x37d95780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d95790: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d957a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
-   0x37d957b0: 00 00 00 00 f1 f1 f1 f1 f1 f1 f8 f2 f8 f3 f3 f3
-   0x37d957c0: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
- Shadow byte legend (one shadow byte represents 8 application bytes):
-   Addressable:           00
-   Partially addressable: 01 02 03 04 05 06 07 
-   Heap left redzone:       fa
-   Freed heap region:       fd
-   Stack left redzone:      f1
-   Stack mid redzone:       f2
-   Stack right redzone:     f3
-   Stack after return:      f5
-   Stack use after scope:   f8
-   Global redzone:          f9
-   Global init order:       f6
-   Poisoned by user:        f7
-   Container overflow:      fc
-   Array cookie:            ac
-   Intra object redzone:    bb
-   ASan internal:           fe
-   Left alloca redzone:     ca
-   Right alloca redzone:    cb
-   Shadow gap:              cc
- ==30226==ABORTING
 : Standard error does not match
```

with Debug enabed. Confusing error...

**Comment by neheb** [comment]
```
auto p = fs::path("/proc/self/exe");
```

is enough to trigger that error. Some glibc or libstdc++ bug. I give up.

**Comment by kevinbackhouse** [comment]
> ```
> auto p = fs::path("/proc/self/exe");
> ```
> 
> is enough to trigger that error. Some glibc or libstdc++ bug. I give up.

Is that on arm32?

**Comment by neheb** [comment]
Reopening this as this happens still. Sample github actions run

https://github.com/neheb/exiv2/actions/runs/12042022653

```
 FAIL: test_run (github.test_CVE_2018_12265.AdditionOverflowInLoaderExifJpeg.test_run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/exiv2/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/runner/work/exiv2/exiv2/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/home/runner/work/exiv2/exiv2/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Erro[319 chars]ata area; ignored.\n' != 'Erro[319 chars]ata area; ignored.\nUncaught exception: Overflow in addition\n'
  Error: Upper boundary of data for directory Image, entry 0x00fe is out of bounds: Offset = 0x0000002a, size = 64, exceeds buffer size by 22 Bytes; truncating the entry
  Warning: Directory Image, entry 0x0201: Strip 0 is outside of the data area; ignored.
  Warning: Directory Image, entry 0x0201: Strip 7 is outside of the data area; ignored.
+ Uncaught exception: Overflow in addition
 : Standard error does not match
```

So, this is happening on ARM32. x86 seems fine. I wonder why...

**Comment by kevinbackhouse** [comment]
@neheb: is that the main branch running on ARM32, or did you make some code changes?

**Comment by neheb** [comment]
it's the main branch. Only change I made was to add extra CI.

**Comment by kevinbackhouse** [comment]
This will be annoying to debug due to the ARM32 hardware. Do you have a debug setup for that?

**Comment by neheb** [comment]
I do. What you need?

**Comment by Gelbpunkt** [comment]
> This will be annoying to debug due to the ARM32 hardware. Do you have a debug setup for that?

Hi, I'm also running into this issue. Is there anything I can do to help you debug this?

**Comment by neheb** [comment]
the is_64bit function seems to work properly so no idea what's going on.

**Comment by neheb** [comment]
Oh I see. The overflow is only on x86 and not ARM32.
