### ISSUE TITLE
lenstest fails on mips64 (big endian)

### ISSUE THREAD

**Issue by neheb** [Exiv2/exiv2#2598]
#### **Describe the bug**
test succeeds
#### **To Reproduce**
```
======================================================================
FAIL: test_run (test_config_file.TestLensConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 653, in test_run
    self.compare_stdout(i, command, processed_stdout, stdout)
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 768, in compare_stdout
    msg="Standard output does not match"
  File "/home/mangix/devstuff/exiv2/tests/system_tests.py", line 746, in _compare_output
    expected, got, msg=msg
AssertionError: 'Exif[30 chars]           Byte        1  Sigma 120-300mm F2.8 DG OS HSM | S\n' != 'Exif[30 chars]           Byte        1  TEST CONFIGURATION FILE!\n'
- Exif.NikonLd3.LensIDNumber                   Byte        1  Sigma 120-300mm F2.8 DG OS HSM | S
+ Exif.NikonLd3.LensIDNumber                   Byte        1  TEST CONFIGURATION FILE!
 : Standard output does not match
```

#### **Additional context**
Same as https://github.com/Exiv2/exiv2/issues/2597

**Comment by neheb** [comment]
ping @kevinbackhouse

**Comment by neheb** [comment]
hmm I reproduced on arm64, I think it's a compile options issue.

**Comment by sertonix** [comment]
I got this failure when using `-DEXIV2_ENABLE_INIH=OFF`. Wouldn't it be better to automatically skip the test in that case?
