### ISSUE TITLE
Unit tests for 0.28.0 fails on FreeBSD 13.2-RELEASE

### ISSUE THREAD

**Issue by diizzyy** [Exiv2/exiv2#2641]
Unit tests fails, it's likely due to some minor issue but I can't find any obvious reason to why.

```
Traceback (most recent call last):
  File "/usr/ports/graphics/exiv2/work/exiv2-0.28.0-Source/tests/runner.py", line 11, in <module>
    import system_tests
  File "/usr/ports/graphics/exiv2/work/exiv2-0.28.0-Source/tests/system_tests.py", line 13, in <module>
    from bash_tests import utils as BT
  File "/usr/ports/graphics/exiv2/work/exiv2-0.28.0-Source/tests/bash_tests/utils.py", line 37, in <module>
    class Config:
  File "/usr/ports/graphics/exiv2/work/exiv2-0.28.0-Source/tests/bash_tests/utils.py", line 60, in Config
    is_64bit = exiv2_is_64bit(bin_dir)
  File "/usr/ports/graphics/exiv2/work/exiv2-0.28.0-Source/tests/bash_tests/utils.py", line 25, in exiv2_is_64bit
    proc.check_returncode()
  File "/usr/local/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/ports/graphics/exiv2/work/.build/bin/exiv2', '--verbose', '--version']' died with <Signals.SIGSEGV: 11>.
```
 Repeats for several more tests:

Output executing exiv2 manually with switches listed above:
```
exiv2 --verbose --version
exiv2 0.28.0
exiv2=0.28.0
platform=freebsd
compiler=Clang
bits=64
dll=1
debug=0
cplusplus=201703
version=FreeBSD Clang 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
date=May 29 2023
time=21:38:51
processpath=/usr/ports/graphics/exiv2/work/.build/bin
package_name=exiv2
curl=0
executable=/usr/ports/graphics/exiv2/work/.build/bin/exiv2
library=/dev/pts/0
library=/usr/ports/graphics/exiv2
library=/usr/lib/libc++.so.1
library=/usr/ports/graphics/exiv2/work/.build/lib/libexiv2.so.0.28.0
library=/lib/libcxxrt.so.1
library=/lib/libm.so.5
library=/lib/libgcc_s.so.1
library=/lib/libc.so.7
library=/usr/local/lib/libexpat.so.1.8.10
library=/usr/lib/libprocstat.so.1
library=/lib/libz.so.6
library=/usr/local/lib/libbrotlicommon.so.1.0.9
library=/usr/local/lib/libbrotlidec.so.1.0.9
library=/usr/local/lib/libiconv.so.2.6.1
library=/usr/local/lib/libINIReader.so.0
library=/usr/local/lib/libinih.so.0
library=/lib/libelf.so.2
library=/lib/libkvm.so.7
library=/lib/libutil.so.9
library=/libexec/ld-elf.so.1
have_inttypes=1
have_libintl=1
have_lensdata=1
have_iconv=1
have_memory=1
have_stdbool=1
have_stdint=1
have_stdlib=1
have_strlib=0
have_strerror_r=1
have_strings_h=0
have_mmap=1
have_munmap=1
have_sys_stat=1
have_unistd_h=0
have_sys_mman=1
have_libz=1
have_brotli=1
have_xmptoolkit=1
adobe_xmpsdk=0
have_bool=0
have_strings=1
have_sys_types=1
have_unistd=1
enable_bmff=1
enable_webready=0
enable_nls=0
enable_video=1
use_curl=0
config_path=/root/.exiv2
uid=0
euid=0
gid=0
xmlns=DICOM:http://ns.adobe.com/DICOM/
xmlns=GPano:http://ns.google.com/photos/1.0/panorama/
xmlns=Iptc4xmpCore:http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/
xmlns=Iptc4xmpExt:http://iptc.org/std/Iptc4xmpExt/2008-02-29/
xmlns=MP:http://ns.microsoft.com/photo/1.2/
xmlns=MPRI:http://ns.microsoft.com/photo/1.2/t/RegionInfo#
xmlns=MPReg:http://ns.microsoft.com/photo/1.2/t/Region#
xmlns=MicrosoftPhoto:http://ns.microsoft.com/photo/1.0/
xmlns=acdsee:http://ns.acdsee.com/iptc/1.0/
xmlns=album:http://ns.adobe.com/album/1.0/
xmlns=asf:http://ns.adobe.com/asf/1.0/
xmlns=audio:http://www.audio/
xmlns=aux:http://ns.adobe.com/exif/1.0/aux/
xmlns=bmsp:http://ns.adobe.com/StockPhoto/1.0/
xmlns=creatorAtom:http://ns.adobe.com/creatorAtom/1.0/
xmlns=crs:http://ns.adobe.com/camera-raw-settings/1.0/
xmlns=crss:http://ns.adobe.com/camera-raw-saved-settings/1.0/
xmlns=dc:http://purl.org/dc/elements/1.1/
xmlns=dcterms:http://purl.org/dc/terms/
xmlns=digiKam:http://www.digikam.org/ns/1.0/
xmlns=dwc:http://rs.tdwg.org/dwc/index.htm
xmlns=exif:http://ns.adobe.com/exif/1.0/
xmlns=exifEX:http://cipa.jp/exif/1.0/
xmlns=expressionmedia:http://ns.microsoft.com/expressionmedia/1.0/
xmlns=iX:http://ns.adobe.com/iX/1.0/
xmlns=jp2k:http://ns.adobe.com/jp2k/1.0/
xmlns=jpeg:http://ns.adobe.com/jpeg/1.0/
xmlns=kipi:http://www.digikam.org/ns/kipi/1.0/
xmlns=lr:http://ns.adobe.com/lightroom/1.0/
xmlns=mediapro:http://ns.iview-multimedia.com/mediapro/1.0/
xmlns=mwg-kw:http://www.metadataworkinggroup.com/schemas/keywords/
xmlns=mwg-rs:http://www.metadataworkinggroup.com/schemas/regions/
xmlns=pdf:http://ns.adobe.com/pdf/1.3/
xmlns=pdfaExtension:http://www.aiim.org/pdfa/ns/extension/
xmlns=pdfaField:http://www.aiim.org/pdfa/ns/field#
xmlns=pdfaProperty:http://www.aiim.org/pdfa/ns/property#
xmlns=pdfaSchema:http://www.aiim.org/pdfa/ns/schema#
xmlns=pdfaType:http://www.aiim.org/pdfa/ns/type#
xmlns=pdfaid:http://www.aiim.org/pdfa/ns/id/
xmlns=pdfx:http://ns.adobe.com/pdfx/1.3/
xmlns=pdfxid:http://www.npes.org/pdfx/ns/id/
xmlns=photoshop:http://ns.adobe.com/photoshop/1.0/
xmlns=plus:http://ns.useplus.org/ldf/xmp/1.0/
xmlns=png:http://ns.adobe.com/png/1.0/
xmlns=rdf:http://www.w3.org/1999/02/22-rdf-syntax-ns#
xmlns=stArea:http://ns.adobe.com/xmp/sType/Area#
xmlns=stDim:http://ns.adobe.com/xap/1.0/sType/Dimensions#
xmlns=stEvt:http://ns.adobe.com/xap/1.0/sType/ResourceEvent#
xmlns=stFnt:http://ns.adobe.com/xap/1.0/sType/Font#
xmlns=stJob:http://ns.adobe.com/xap/1.0/sType/Job#
xmlns=stMfs:http://ns.adobe.com/xap/1.0/sType/ManifestItem#
xmlns=stRef:http://ns.adobe.com/xap/1.0/sType/ResourceRef#
xmlns=stVer:http://ns.adobe.com/xap/1.0/sType/Version#
xmlns=tiff:http://ns.adobe.com/tiff/1.0/
xmlns=video:http://www.video/
xmlns=wav:http://ns.adobe.com/xmp/wav/1.0/
xmlns=xml:http://www.w3.org/XML/1998/namespace
xmlns=xmp:http://ns.adobe.com/xap/1.0/
xmlns=xmpBJ:http://ns.adobe.com/xap/1.0/bj/
xmlns=xmpDM:http://ns.adobe.com/xmp/1.0/DynamicMedia/
xmlns=xmpG:http://ns.adobe.com/xap/1.0/g/
xmlns=xmpGImg:http://ns.adobe.com/xap/1.0/g/img/
xmlns=xmpMM:http://ns.adobe.com/xap/1.0/mm/
xmlns=xmpNote:http://ns.adobe.com/xmp/note/
xmlns=xmpRights:http://ns.adobe.com/xap/1.0/rights/
xmlns=xmpT:http://ns.adobe.com/xap/1.0/t/
xmlns=xmpTPg:http://ns.adobe.com/xap/1.0/t/pg/
xmlns=xmpidq:http://ns.adobe.com/xmp/Identifier/qual/1.0/
```

OS: FreeBSD 13.2-RELEASE (amd64)
Compiler:  LLVM/Clang 14.0.5
CMake 3.26.1
Python 3.9.16
Googletest 1.13.0

**Comment by neheb** [comment]
@diizzyy did https://github.com/Exiv2/exiv2/pull/2672 fix it?

**Comment by diizzyy** [comment]
It works now but Matthias pulled in a bunch of patches so I don't know which one fixed it, possibly https://github.com/Exiv2/exiv2/commit/f47e7bd666aa063d016bdf00ea8f62c97a5b5a7a .

See: https://cgit.freebsd.org/ports/tree/graphics/exiv2
