### ISSUE TITLE
0.28.0: test suite fails in `bugfixTests` unit

### ISSUE THREAD

**Issue by kloczek** [Exiv2/exiv2#2762]
#### **Describe the bug**
Looks like etst suite fails in `bugfixTests` unit.

#### **To Reproduce**
cmake settings:
```console
[tkloczko@pers-jacek x86_64-redhat-linux-gnu]$ cmake -L
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "/home/tkloczko/rpmbuild/BUILD/exiv2-0.28.0/x86_64-redhat-linux-gnu" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
BUILD_SHARED_LIBS:BOOL=ON
BUILD_TESTING:BOOL=ON
BUILD_WITH_CCACHE:BOOL=OFF
BUILD_WITH_COVERAGE:BOOL=OFF
BUILD_WITH_STACK_PROTECTOR:BOOL=ON
CMAKE_BUILD_TYPE:STRING=RelWithDebInfo
CMAKE_INSTALL_PREFIX:PATH=/usr
CXX_FILESYSTEM_HAVE_FS:BOOL=TRUE
CXX_FILESYSTEM_HEADER:STRING=filesystem
CXX_FILESYSTEM_IS_EXPERIMENTAL:BOOL=FALSE
CXX_FILESYSTEM_NAMESPACE:STRING=std::filesystem
EXIV2_BUILD_DOC:BOOL=ON
EXIV2_BUILD_EXIV2_COMMAND:BOOL=ON
EXIV2_BUILD_FUZZ_TESTS:BOOL=OFF
EXIV2_BUILD_SAMPLES:BOOL=OFF
EXIV2_BUILD_UNIT_TESTS:BOOL=ON
EXIV2_ENABLE_BMFF:BOOL=ON
EXIV2_ENABLE_BROTLI:BOOL=ON
EXIV2_ENABLE_CURL:BOOL=OFF
EXIV2_ENABLE_DYNAMIC_RUNTIME:BOOL=ON
EXIV2_ENABLE_INIH:BOOL=ON
EXIV2_ENABLE_LENSDATA:BOOL=ON
EXIV2_ENABLE_NLS:BOOL=ON
EXIV2_ENABLE_PNG:BOOL=ON
EXIV2_ENABLE_VIDEO:BOOL=ON
EXIV2_ENABLE_WEBREADY:BOOL=ON
EXIV2_ENABLE_XMP:BOOL=ON
EXIV2_TEAM_OSS_FUZZ:BOOL=OFF
EXIV2_TEAM_PACKAGING:BOOL=OFF
Filesystem_FOUND:BOOL=TRUE
GETTEXT_MSGFMT_EXECUTABLE:FILEPATH=/usr/bin/msgfmt
GETTEXT_MSGMERGE_EXECUTABLE:FILEPATH=/usr/bin/msgmerge
XGETTEXT:FILEPATH=/usr/bin/xgettext
```

#### **Expected behavior**
Test suite should not fail.

#### **Desktop (please complete the following information):**
- OS and version: Linux x86/64
- Exiv2 version and source: 0.28.0
- Compiler and version: (gcc 13.2.1
- Compilation mode and/or compiler flags: -O2 + LTO

#### **Additional context**
Test suite output
<details>

```console
+ cd exiv2-0.28.0
+ /usr/bin/ctest --test-dir x86_64-redhat-linux-gnu --output-on-failure --force-new-ctest-process -j48
Internal ctest changing into directory: /home/tkloczko/rpmbuild/BUILD/exiv2-0.28.0/x86_64-redhat-linux-gnu
Test project /home/tkloczko/rpmbuild/BUILD/exiv2-0.28.0/x86_64-redhat-linux-gnu
    Start 1: bugfixTests
    Start 2: lensTests
    Start 3: tiffTests
    Start 4: versionTests
    Start 5: regressionTests
    Start 6: unitTests
1/6 Test #6: unitTests ........................   Passed    0.02 sec
2/6 Test #4: versionTests .....................   Passed    0.20 sec
3/6 Test #3: tiffTests ........................   Passed    0.21 sec
4/6 Test #2: lensTests ........................   Passed    0.28 sec
5/6 Test #5: regressionTests ..................   Passed    6.53 sec
6/6 Test #1: bugfixTests ......................***Failed   11.90 sec
test_run (github.test_CVE_2017_1000126.TestCvePoC) ... ok
test_run (github.test_CVE_2017_1000127.TestPoC) ... ok
test_run (github.test_CVE_2017_11336.TestCvePoC) ... ok
test_run (github.test_CVE_2017_11337.TestCvePoC) ... ok
test_run (github.test_CVE_2017_11338.TestCvePoC) ... ok
test_run (github.test_CVE_2017_11339.TestCvePoC) ... ok
test_run (github.test_CVE_2017_11340.TestCvePoC) ... ok
test_run (github.test_CVE_2017_11553.TestCvePoC) ... ok
test_run (github.test_CVE_2017_11591.TestCvePoC) ... ok
test_run (github.test_CVE_2017_11592.TestCvePoC) ... ok
test_run (github.test_CVE_2017_11683.TestCvePoC) ... ok
test_run (github.test_CVE_2017_12955.TestCvePoC) ... ok
test_run (github.test_CVE_2017_12956.TestCvePoC) ... ok
test_run (github.test_CVE_2017_12957.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14857.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14858.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14859.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14860.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14861.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14862.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14863.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14864.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14865.TestCvePoC) ... ok
test_run (github.test_CVE_2017_14866.TestCvePoC) ... ok
test_run (github.test_CVE_2017_17669.TestCvePoC) ... ok
test_run (github.test_CVE_2017_17722.TestCvePoC) ... ok
test_run (github.test_CVE_2017_17724.TestFuzzedPoC) ... ok
test_run (github.test_CVE_2017_17725.TestCvePoC) ... ok
test_run (github.test_CVE_2017_18005.TestPoC) ... ok
test_run (github.test_CVE_2017_9953.TestCvePoC) ... ok
test_run (github.test_CVE_2018_10999.TestCvePoC) ... ok
test_run (github.test_CVE_2018_11531.TestCvePoC) ... ok
test_run (github.test_CVE_2018_12264.AdditionOverflowInLoaderTiffGetData) ... ok
test_run (github.test_CVE_2018_12265.AdditionOverflowInLoaderExifJpeg) ... ok
test_run (github.test_CVE_2018_2018_14046.WebpDecodeChunksOutOfBoundsRead) ... ok
test_run (github.test_CVE_2018_4868.TestCvePoC) ... ok
test_run (github.test_CVE_2018_9145.SubBoxLengthDataBufAbort) ... skipped 'Skipping test using option -pR (only for Debug mode)'
test_run (github.test_coverage_xmp_doctype.coverage_xmp_doctype) ... ok
test_run (github.test_coverage_xmpsidecar_isXmpType.coverage_xmpsidecar_isXmpType) ... ok
test_run (github.test_fuji_tags.FujiTags) ... ok
test_run (github.test_issue_1011.Test_issue_1011) ... ok
test_run (github.test_issue_1014.NikonLens) ... ok
test_run (github.test_issue_1019.OverreadInCiffDirectoryReadDirectory) ... ok
test_run (github.test_issue_1046.test_issue_1046Test) ... ok
test_run (github.test_issue_1069.NikonTamronLens_F045_35_F14) ... ok
test_run (github.test_issue_1078.NikonTokinaLens_atx_i_11_16_F28) ... ok
test_run (github.test_issue_1097.InfiniteRecursionInCiffDirectoryReadDirectory) ... ok
test_run (github.test_issue_1099.EmptyValueInCommandFile) ... ok
test_run (github.test_issue_1180.test_issue_1180Test) ... ok
test_run (github.test_issue_1208.Sigma_Art_85mm_F1_4Nikon_F_mount) ... ok
test_run (github.test_issue_1368.Canon_Sigma_18_35_F18_DC_HSM) ... ok
test_run (github.test_issue_1464.test_issue_1464Test) ... ok
test_run (github.test_issue_1471.test_issue_1471Test) ... ok
test_run (github.test_issue_1472.test_issue_1472Test) ... ok
test_run (github.test_issue_1473.test_issue_1473) ... ok
test_run (github.test_issue_1484.test_issue_1484) ... ok
test_run (github.test_issue_1503.issue_1503_jxl_bmff) ... ok
test_run (github.test_issue_1522.issue_1522_exif_asan) ... ok
test_run (github.test_issue_1530.CrwEncode0x1810IntegerOverflow) ... ok
test_run (github.test_issue_1570.BmffImageReadMetadataOutOfBoundsRead) ... ok
test_run (github.test_issue_159.TestFirstPoC) ... ok
test_run (github.test_issue_170.DecodeIHDRChunkOutOfBoundsRead) ... ok
test_run (github.test_issue_1706.InvalidDateXMP) ... ok
test_run (github.test_issue_1713.InvalidDateXMP) ... ok
test_run (github.test_issue_1723.Olympus_MZuiko_12_45mm_f4_Pro) ... ok
test_run (github.test_issue_1763.CanonPrintCsLensTypeByMetadataNullIteratorDeref) ... ok
test_run (github.test_issue_1782.test_issue_1782) ... ok
test_run (github.test_issue_1791.RafNoTiffRegression) ... ok
test_run (github.test_issue_1793.BmffImageboxHandlerLargeAllocation) ... ok
test_run (github.test_issue_1805.exiv2pRHeaderTest) ... skipped 'Skipping test using option -pR (only for Debug mode)'
test_run (github.test_issue_1812.OutOfMemoryInJp2ImageReadMetadata) ... ok
test_run (github.test_issue_1815.JpgImageDoWriteMetadataOutOfBoundsRead) ... ok
test_run (github.test_issue_1817.MemoryLeakInPngImagePrintStructure) ... ok
test_run (github.test_issue_1819.EmptyStringXmpTextValueRead) ... ok
test_run (github.test_issue_1821.MemoryLeakAddBinding) ... skipped 'Skipping test until #1821 is fixed'
test_run (github.test_issue_1827.ExposureTimeCastDoubleToLong) ... ok
test_run (github.test_issue_1830.ValueTypeFloatToLong) ... ok
test_run (github.test_issue_1833.TiffMnEntryDoCountInvalidTiffType) ... ok
test_run (github.test_issue_1838.FloatToRationalCastOutOfRange) ... ok
test_run (github.test_issue_1841.MemoryLeakWebPImageDecodeChunks) ... ok
test_run (github.test_issue_1845.TiffDirectoryWriteDirEntryAssert) ... ok
test_run (github.test_issue_1847.TiffMnEntryDoCountInvalidTiffType) ... ok
test_run (github.test_issue_1881.SonyPreviewImageLargeAllocation) ... ok
test_run (github.test_issue_1887.OutOfBoundsReadInCrwMapDecode0x080a) ... ok
test_run (github.test_issue_1893.issue_1893_cr3_preview) ... ok
test_run (github.test_issue_1901.XMPUtilsSetTimeZoneIntegerOverflow) ... ok
test_run (github.test_issue_1912.TagsIntPrint0x0007IntegerOverflow) ... ok
test_run (github.test_issue_1918.PrintXmpDateOutOfBoundsIndex19) ... ok
test_run (github.test_issue_1920.PentaxMakerNotePrintTimeSignedLeftShift) ... ok
test_run (github.test_issue_1941.TestNikonFl7GroupWithFlash) ... ok
test_run (github.test_issue_1941.TestNikonFl7GroupWithoutFlash) ... ok
test_run (github.test_issue_1954.XMPUtilsLeapYearOverflow) ... ok
test_run (github.test_issue_1969.TestPrintPlainWithSet) ... ok
test_run (github.test_issue_20.TamronSupport) ... ok
test_run (github.test_issue_2006.PanasonicMakerPrintAccelerometerIntOverflow) ... ok
test_run (github.test_issue_211.TestFuzzedPoC) ... ok
test_run (github.test_issue_2126.OMSystemMakerNote) ... ok
test_run (github.test_issue_216.UncontrolledRecursion) ... skipped 'Skipping test using option -pR (only for Debug mode)'
test_run (github.test_issue_2233.TestJXLBoxEndExif) ... ok
test_run (github.test_issue_2233.TestJXLBoxEndXML) ... ok
test_run (github.test_issue_2246.OlympusArtFilterPartialColor) ... ok
test_run (github.test_issue_2268.issue_2268_jp2_assert) ... ok
test_run (github.test_issue_227.SigmaLenses) ... ok
test_run (github.test_issue_2270.WebPImage_inject_VP8X_integer_overflow) ... ok
test_run (github.test_issue_2320.issue_2320_printDegrees_integer_overflow) ... ok
test_run (github.test_issue_2339.issue_2339_printDegrees_integer_overflow) ... ok
test_run (github.test_issue_2340.issue_2320_printDegrees_integer_overflow) ... ok
test_run (github.test_issue_2345.issue_2345_QuickTimeVideo_tagDecoder_buffer_overflow) ... ok
test_run (github.test_issue_2352.issue_2352_floatToRationalCast_integer_overflow) ... ok
test_run (github.test_issue_2366.issue_2366_QuickTimeVideo_userDataDecoder_buffer_overflow) ... ok
test_run (github.test_issue_2376.issue_2376_QuickTimeVideo_userDataDecoder_null_deref) ... ok
test_run (github.test_issue_2377.issue_2377_QuickTimeVideo_userDataDecoder_buffer_overflow) ... ok
test_run (github.test_issue_2383.issue_2383_QuickTimeVideo_userDataDecoder_null_deref) ... ok
test_run (github.test_issue_2385.issue_2385_printColorCompensationFilter_integer_overflow) ... ok
test_run (github.test_issue_2393.issue_2393_QuickTimeVideo_multipleEntriesDecoder_long_running) ... ok
test_run (github.test_issue_2403.checkIconvSegFault) ... ok
test_run (github.test_issue_2423.issue_2423_QuickTimeVideo_sampleDesc_long_running) ... ok
test_run (github.test_issue_2427.issue_2427_BmffImage_brotliUncompress_memleak) ... FAIL
test_run (github.test_issue_246.TestFirstPoC) ... ok
test_run (github.test_issue_247.TestFirstPoC) ... ok
test_run (github.test_issue_253.TestFirstPoC) ... ok
test_run (github.test_issue_2542.OMSystemMakerNoteAlias) ... ok
test_run (github.test_issue_262.DivByZeroInPrintIFD) ... ok
test_run (github.test_issue_263.OutOfBoundsReadInPrintStructure) ... ok
test_run (github.test_issue_400.parseTXTChunkOutOfBoundsRead) ... ok
test_run (github.test_issue_426.DetectsWrongLengthOfImageResourceInPSDFile) ... ok
test_run (github.test_issue_428.PngReadRawProfile) ... ok
test_run (github.test_issue_45.Sigma24_105mmRecognition) ... ok
test_run (github.test_issue_457.ThrowsWhenColorProfileInTiffMetadataIsCorrupted) ... ok
test_run (github.test_issue_460.ThrowsWhenCRWImageIsMalformed) ... ok
test_run (github.test_issue_511.ThrowsWhenIFDsAreMalformed) ... skipped 'Skipping test using option -pR (only for Debug mode)'
test_run (github.test_issue_547.test_issue_547) ... skipped 'Skipping test using option -pR (only for Debug mode)'
test_run (github.test_issue_561.ShouldNotThrowsWithSpecificIsoSpeedValue) ... ok
test_run (github.test_issue_590.TiffImageIntOutOfBoundsRead) ... ok
test_run (github.test_issue_598.NikonTamronLens_A030_70_300_F4_56) ... ok
test_run (github.test_issue_646.Fix646_NikonAF22) ... ok
test_run (github.test_issue_712.BigTiffImageRecursionStackExhaustion) ... ok
test_run (github.test_issue_742.ThrowsWhenSubBoxLengthIsNotGood) ... ok
test_run (github.test_issue_743.Issue743NikonSigmaArtLens) ... ok
test_run (github.test_issue_756.BufferOverReadInNikon1MakerNotePrint0x0088) ... ok
test_run (github.test_issue_789.SegvInPngImageReadMetadata) ... ok
test_run (github.test_issue_790.IntegerOverflowInPngImageReadMetadata) ... ok
test_run (github.test_issue_791.IntegerOverflowInWebpImageReadMetadata) ... ok
test_run (github.test_issue_818.TestDefaultCommandGrep) ... ok
test_run (github.test_issue_828.SegmentationFaultPngImage) ... skipped 'Skipping test using option -pR (only for Debug mode)'
test_run (github.test_issue_839.OutOfMemoryInLoaderTiffGetData) ... ok
test_run (github.test_issue_841.InvalidDataLocationInCiffComponentDoRead) ... ok
test_run (github.test_issue_843.IntegerOverflowInCiffDirectoryReadDirectory) ... ok
test_run (github.test_issue_845.LargeAllocationInPngChunk) ... ok
test_run (github.test_issue_847.LargeAllocationInPgfReadMetadata) ... ok
test_run (github.test_issue_851.DenialOfServiceInAdjustTimeOverflow) ... ok
test_run (github.test_issue_853.DenialOfServiceInAdjustTimeOverflow) ... ok
test_run (github.test_issue_855.OutOfMemoryInPsdImageReadMetadata) ... ok
test_run (github.test_issue_857.OutOfMemoryInRafImageReadMetadata) ... ok
test_run (github.test_issue_867.OutOfBoundsReadInIptcParserDecode) ... ok
test_run (github.test_issue_869.OutOfBoundsReadInIptcParserDecode) ... ok
test_run (github.test_issue_943.MrmImageLargeAllocation) ... ok
test_run (github.test_issue_960.WebPImageGetHeaderOffset) ... ok
test_run (github.test_issue_981.CanonAfInfoTest) ... ok
test_run (github.test_issue_990.test_issue_990Test) ... ok
test_run (github.test_issue_g44w_q3vm_gwjq.ImagePrintIFDStructureZeroCountAssert) ... skipped 'Skipping test using option -pR (only for Debug mode)'
test_run (github.test_issue_ghsa_583f_w9pm_99r2.Jp2ImagePrintStructureICC) ... ok
test_run (github.test_issue_ghsa_5p8g_9xf3_gfrr.WebPImageDoWriteMetadataOutOfBoundsRead) ... ok
test_run (github.test_issue_ghsa_7569_phvm_vwc2.Jp2ImageDoWriteMetadataOutOfBoundsRead) ... ok
test_run (github.test_issue_ghsa_8949_hhfh_j7rj.Jp2ImageEncodeJp2HeaderOutOfBoundsRead) ... ok
test_run (github.test_issue_ghsa_9jh3_fcc3_g6hv.JpegBasePrintStructureInfiniteLoop) ... ok
test_run (github.test_issue_ghsa_h9x9_4f77_336w.Jp2ImageEncodeJp2HeaderOutOfBoundsRead2) ... ok
test_run (github.test_issue_ghsa_hqjh_hpv8_8r9p.CrwMapDecodeArrayInfiniteLoop) ... ok
test_run (github.test_issue_ghsa_jgm9_5fw5_pw9p.WebPImageDoWriteMetadataOutOfBoundsRead) ... ok
test_run (github.test_issue_ghsa_m479_7frc_gqqg.ImagePrintIFDStructure) ... ok
test_run (github.test_issue_ghsa_mv9g_fxh2_m49m.test_issue_ghsa_mv9g_fxh2_m49m) ... ok
test_run (github.test_issue_ghsa_mvc4_g5pv_4qqq.JpegBasePrintStructureInfiniteLoop) ... ok
test_run (github.test_issue_ghsa_mxw9_qx4c_6m8v.Jp2ImageEncodeJp2HeaderOutOfBoundsRead2) ... ok
test_run (github.test_issue_ghsa_pvjp_m4f6_q984.MinoltaDivZero) ... ok
test_run (github.test_issue_ghsa_v5g7_46xf_h728.Jp2ImageEncodeJp2HeaderOutOfBoundsRead2) ... ok
test_run (github.test_jpg_iptcDataSegs.jpg_iptcDataSegs) ... ok
test_run (github.test_pr1475_AVIF.pr_1475_avif_avif) ... ok
test_run (github.test_pr1475_AVIF.pr_1475_exif_xmp_avif) ... ok
test_run (github.test_pr1475_AVIF.pr_1475_metadata2_avif) ... ok
test_run (github.test_pr1475_HEIC.pr_1475_2021_heic) ... ok
test_run (github.test_pr1475_HEIC.pr_1475_IMG_3578_heic) ... ok
test_run (github.test_pr1475_HEIC.pr_1475_Stonehenge_heic) ... ok
test_run (github.test_pr1475_HEIC.pr_1475_heic_heic) ... ok
test_run (github.test_pr1475_HIF.pr_1475_Canon_hif) ... ok
test_run (github.test_pr1475_HIF.pr_1475_Sony_hif) ... ok
test_run (github.test_pr_1105.Tamron_17_35_Di_OSD) ... ok
test_run (github.test_pr_1375.Olympus_MZuiko_17mm_f12_Pro) ... ok
test_run (github.test_pr_1384.test_pr_1384) ... ok
test_run (github.test_pr_1409.FujiFilm_IFD_Tags_pr1409) ... ok
test_run (github.test_pr_1436.DNG_1_6_Tags_pr1436) ... ok
test_run (github.test_pr_1437.Nikon_LensData8) ... ok
test_run (github.test_pr_1456.CanonSigmaLens_14_24mm_F28_DG_HSM_A) ... ok
test_run (github.test_pr_1456.CanonSigmaLens_28mm_F14_DG_HSM_A) ... ok
test_run (github.test_pr_1456.CanonSigmaLens_35mm_F14_DG_HSM_A) ... ok
test_run (github.test_pr_1456.CanonSigmaLens_40mm_F14_DG_HSM_A) ... ok
test_run (github.test_pr_1456.CanonSigmaLens_50mm_F14_DG_HSM_A) ... ok
test_run (github.test_pr_1456.CanonSigmaLens_60_600mm_F45_63_DG_OS_HSM_S) ... ok
test_run (github.test_pr_1688.Canon_EF_100_400mm_F45_56_2x) ... ok
test_run (github.test_pr_1691.Tamron_SP_24_70mm_F28_Di_VC_USD_G2_0E) ... ok
test_run (github.test_pr_1772.SonyMisc1Test) ... ok
test_run (github.test_pr_1792.SonyMisc2bTestSupported) ... ok
test_run (github.test_pr_1792.SonyMisc2bTestUnsupported) ... ok
test_run (github.test_pr_1800.SonyMisc3cPartiallySupportedTest) ... ok
test_run (github.test_pr_1800.SonyMisc3cSupportedTest) ... ok
test_run (github.test_pr_1800.SonyMisc3cUnsupportedTest) ... ok
test_run (github.test_pr_1808.SonyMisc3cSupportedTest) ... ok
test_run (github.test_pr_1926.Sony2FpAmbientTemperatureUnsupportedTagTest) ... ok
test_run (github.test_pr_1926.SonyMisc1CameraTemperatureUnsupportedTagTest) ... ok
test_run (github.test_pr_1979.TestExiv2ExtractThumbnailToStdout) ... ok
test_run (github.test_pr_1994.TestAddModelsForNikonFl3) ... ok
test_run (github.test_pr_1999.TestXmpDateTimeSetting) ... ok
test_run (github.test_pr_2000.TestVerboseExtractCommentToStdout) ... ok
test_run (github.test_pr_2000.TestVerboseExtractICCProfileToStdout) ... ok
test_run (github.test_pr_2000.TestVerboseExtractRawMetadataToStdout) ... ok
test_run (github.test_pr_2000.TestVerboseExtractThumbnailToStdout) ... ok
test_run (github.test_pr_2000.TestVerboseExtractXmpSidecarToStdout) ... ok
test_run (github.test_pr_2000.TestVerboseModifyDelExtractXmpSidecarToStdout) ... ok
test_run (github.test_pr_2000.TestVerboseModifyRegAddExtractXmpSidecarToStdout) ... ok
test_run (github.test_pr_2000.TestVerboseModifySetExtractXmpSidecarToStdout) ... ok
test_run (github.test_pr_2068.TestVerboseExtractStdoutMultiFile) ... ok
test_run (github.test_pr_2069.NikonSigmaLens_APO_MACRO_180_F35_EX_DG_HSM) ... ok
test_run (github.test_pr_2072.NikonTokinaLens_ATX_i_11_20mm_F2_8_CF) ... ok
test_run (github.test_pr_2073.NikonTokinaLens_AT_X_14_20_F2_PRO_DX) ... ok
test_run (github.test_pr_2244.test_pr_2244) ... ok
test_run (github.test_pr_2586.FailToReadJpgImageTest) ... ok
test_run (github.test_pr_317.CanonEOSM100) ... ok
test_run (github.test_pr_906.Sony2FpTest) ... ok
test_run (github.test_pr_992.NikonSigmaLens_APO_MACRO_180_F35_EX_DG_HSM) ... ok
test_run (github.test_regression_issue_201.ShadowingError) ... ok
test_run (redmine.test_1305.Issue1305Test) ... ok
test_run (redmine.test_426.ReadIPTfromJPEG) ... ok
test_run (redmine.test_440.IPTCtimeWithoutTimeZone) ... ok
test_run (redmine.test_issue_1024.CheckRegularExpressionSupport) ... ok
test_run (redmine.test_issue_1026.CheckLensZoomNikkor) ... ok
test_run (redmine.test_issue_1040.CheckMWG_KW_Schema) ... ok
test_run (redmine.test_issue_1043.FailureOnCifsShares) ... ok
test_run (redmine.test_issue_1044.CheckTiffPageNumber) ... ok
test_run (redmine.test_issue_1053.CheckOptionK) ... ok
test_run (redmine.test_issue_1058.CheckXmlLang) ... ok
test_run (redmine.test_issue_1062.CheckNikonTimezoneWithoutCruft) ... ok
test_run (redmine.test_issue_1074.IccProfileInApp2Segment) ... ok
test_run (redmine.test_issue_1080.CheckDivisionByZero) ... ok
test_run (redmine.test_issue_1108.CheckDumpSubFiles) ... skipped 'Skipping test using option -pR (only for Debug mode)'
test_run (redmine.test_issue_1112.CheckXmpTimeZoneInformation) ... ok
test_run (redmine.test_issue_1114.CheckNegativeValuesOfSByte) ... ok
test_run (redmine.test_issue_1122.CheckLensDetectionTeleconverter) ... ok
test_run (redmine.test_issue_1137.MetadataPiping) ... ok
test_run (redmine.test_issue_1140.CheckCanonLenses) ... ok
test_run (redmine.test_issue_1144.CheckPentaxK10) ... ok
test_run (redmine.test_issue_1145.CheckSonyMinoltaLenses) ... ok
test_run (redmine.test_issue_1153.CheckSony6000WithoutLensModels) ... ok
test_run (redmine.test_issue_1155.CheckPentaxK3) ... ok
test_run (redmine.test_issue_1166.CheckTokina11_20mm) ... ok
test_run (redmine.test_issue_1167.CheckSigma17_70Lens) ... ok
test_run (redmine.test_issue_1170.CheckSigma35mm) ... ok
test_run (redmine.test_issue_1179.CheckFilmMode) ... ok
test_run (redmine.test_issue_1202.CheckFocusContinuous) ... ok
test_run (redmine.test_issue_1223.CheckShutterInPentax) ... ok
test_run (redmine.test_issue_1225.CheckBarometer) ... ok
test_run (redmine.test_issue_1229.CheckXmpData) ... ok
test_run (redmine.test_issue_1231.CheckTimeZones) ... ok
test_run (redmine.test_issue_1242.CheckShutterInPentax) ... ok
test_run (redmine.test_issue_1247.NotValidIccProfile) ... ok
test_run (redmine.test_issue_1252.CanonLenses) ... ok
test_run (redmine.test_issue_1305.PentaxImageWithIssues) ... ok
test_run (redmine.test_issue_1348.NikonLensId227) ... ok
test_run (redmine.test_issue_443.CorruptedIopDir) ... ok
test_run (redmine.test_issue_444.PanicOnMisinformedIPTC) ... ok
test_run (redmine.test_issue_445.SetCommentOnImageWithEmptyComment) ... ok
test_run (redmine.test_issue_447.BufferOverflowInSscanf) ... ok
test_run (redmine.test_issue_452.NonIntrusiveWriteUpdateIFD) ... ok
test_run (redmine.test_issue_460.EncodingTest) ... ok
test_run (redmine.test_issue_479.CrashAfterLightzoneEdit) ... ok
test_run (redmine.test_issue_495.CorruptedIopDirectory) ... ok
test_run (redmine.test_issue_498.ReadDataAfterTagDelete) ... ok
test_run (redmine.test_issue_501.IptcFieldParsingTooStrict) ... ok
test_run (redmine.test_issue_528.TypeSizeForExifOnly) ... ok
test_run (redmine.test_issue_540.PrettyPrintXmp) ... ok
test_run (redmine.test_issue_554.SettingExifImageDateTimeDateGivesValueTooLarge) ... ok
test_run (redmine.test_issue_662.UnicodeEncodingOfExifUserCommentTag) ... ok
test_run (redmine.test_issue_666.OptimizeBinaryArrayElements) ... ok
test_run (redmine.test_issue_683.PercentABrokenInRename) ... ok
test_run (redmine.test_issue_711.BigEndianORFFilesFromE_PL1Corrupted) ... ok
test_run (redmine.test_issue_711.LittleEndianORFFilesFromE_PL1Corrupted) ... ok
test_run (redmine.test_issue_751.AdobeXmpNamespace) ... ok
test_run (redmine.test_issue_769.AssertionSvEqualsDFailedRegression) ... ok
test_run (redmine.test_issue_784.WritingXmpLrHierarchicalSubjectWritesWrongDatatype) ... ok
test_run (redmine.test_issue_799.WrongXmpTypeForNestedXmpKeys) ... ok
test_run (redmine.test_issue_800.MissingPhotoshopIrbTypes) ... ok
test_run (redmine.test_issue_812.DoNotDestroyHardLinks) ... ok
test_run (redmine.test_issue_816.DetectionOfSigma55_200mmLens) ... ok
test_run (redmine.test_issue_825.PanasonicManometerTag) ... ok
test_run (redmine.test_issue_831.UseNonIntrusiveWriting) ... ok
test_run (redmine.test_issue_836.WriteMetadataDestroysResourceForkOnMacOSXForBigFiles) ... skipped 'File system does not support resource forks'
test_run (redmine.test_issue_841.ThrowOnInput) ... ok
test_run (redmine.test_issue_855.DontSegfaultWhenAccessingFocalLength) ... ok
test_run (redmine.test_issue_876.Canon_EF_35mm_f_slash_2_IS_USM_Lens) ... ok
test_run (redmine.test_issue_884.NewTamronAndPentaxLenses) ... ok
test_run (redmine.test_issue_922.AddMinusPSOption) ... ok
test_run (redmine.test_issue_935.FixMetadataDifferenceToExiftool) ... ok
test_run (redmine.test_issue_937.DarwinCoreXmpMetadataModify) ... ok
test_run (redmine.test_issue_937.DarwinCoreXmpMetadataPrint) ... ok

======================================================================
FAIL: test_run (github.test_issue_2427.issue_2427_BmffImage_brotliUncompress_memleak)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/exiv2-0.28.0/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/home/tkloczko/rpmbuild/BUILD/exiv2-0.28.0/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/home/tkloczko/rpmbuild/BUILD/exiv2-0.28.0/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Exiv[73 chars]0.28.0/test/data/issue_2427_poc.jpg:\n_ERROR_FORMAT_CL_SPACE\n' != 'Exiv[73 chars]0.28.0/test/data/issue_2427_poc.jpg:\nCL_SPACE\n'
  Exiv2 exception in print action for file /home/tkloczko/rpmbuild/BUILD/exiv2-0.28.0/test/data/issue_2427_poc.jpg:
- _ERROR_FORMAT_CL_SPACE
+ CL_SPACE
 : Standard error does not match

----------------------------------------------------------------------
Ran 302 tests in 11.264s

FAILED (failures=1, skipped=10)


83% tests passed, 1 tests failed out of 6

Total Test time (real) =  11.91 sec

The following tests FAILED:
          1 - bugfixTests (Failed)
Errors while running CTest
```
</details>

**Comment by kmilos** [comment]
Fixed by https://github.com/Exiv2/exiv2/pull/2816
