### ISSUE TITLE
AddressSanitizer: invalid write (NPE) at value.cpp:212

### ISSUE THREAD

**Issue by HongxuChen** [Exiv2/exiv2#423]
When running `exiv2 $FILE` (5940c6f, disable-printStructure) on some crafted tiff files, ASAN reports an invalid write on a NULL pointer.

POCs:
https://github.com/ntu-sec/pocs/blob/master/exiv2-5940c6f3/crashes/npe_w_value.cpp:212_1.tiff?raw=true
https://github.com/ntu-sec/pocs/blob/master/exiv2-5940c6f3/crashes/npe_w_value.cpp:212_2.tiff?raw=true

ASAN output:
```
Error: Directory Image: Next pointer is out of bounds; ignored.
Error: Directory Image, entry 0x00fe has invalid size 318767105*2; skipping entry.
Error: Upper boundary of data for directory Image, entry 0x0115 is out of bounds: Offset = 0x00000001, size = 16386, exceeds buffer size by 15405 Bytes; truncating the entry
Error: Directory Image, entry 0x0136 has invalid size 774778414*8; skipping entry.
Warning: Directory Image, entry 0x2e2e has unknown Exif (TIFF) type 11822; setting type size 1.
Error: Directory Image, entry 0x2e2e has invalid size 774778414*1; skipping entry.
Warning: Directory Image, entry 0x8773 has unknown Exif (TIFF) type 65031; setting type size 1.
Warning: Directory Image, entry 0x0280 has unknown Exif (TIFF) type 0; setting type size 1.
Error: Offset of directory Image, entry 0x0004 is out of bounds: Offset = 0x01120000; truncating the entry
Error: Offset of directory Image, entry 0x0003 is out of bounds: Offset = 0x66669999; truncating the entry
Warning: Directory Image, entry 0x3333 has unknown Exif (TIFF) type 0; setting type size 1.
Warning: Directory Image, entry 0x0000 has unknown Exif (TIFF) type 0; setting type size 1.
Error: Offset of directory Image, entry 0x0000 is out of bounds: Offset = 0x16000000; truncating the entry
AddressSanitizer:DEADLYSIGNAL
=================================================================
==10074==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000051196a bp 0x7ffe5d9325e0 sp 0x7ffe5d931d60 T0)
==10074==The signal is caused by a WRITE memory access.
==10074==Hint: address points to the zero page.
    #0 0x511969 in __sanitizer::internal_memmove(void*, void const*, unsigned long) (/home/hongxu/FOT/exiv2/install/bin/exiv2+0x511969)
    #1 0x4f4ff4 in __asan_memmove (/home/hongxu/FOT/exiv2/install/bin/exiv2+0x4f4ff4)
    #2 0x7f022fbcc295 in unsigned char* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned char>(unsigned char const*, unsigned char const*, unsigned char*) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_algobase.h:368:6
    #3 0x7f022fc4bb88 in unsigned char* std::__copy_move_a<false, unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_algobase.h:385:14
    #4 0x7f022fcd8feb in unsigned char* std::__copy_move_a2<false, __gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > >, unsigned char*>(__gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > >, unsigned char*) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_algobase.h:422:18
    #5 0x7f022fcc55af in unsigned char* std::copy<__gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > >, unsigned char*>(__gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > >, unsigned char*) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_algobase.h:454:15
    #6 0x7f022fcb4d94 in Exiv2::DataValue::copy(unsigned char*, Exiv2::ByteOrder) const /home/hongxu/FOT/exiv2/src/value.cpp:212:13
    #7 0x7f022fb60d65 in Exiv2::Exifdatum::copy(unsigned char*, Exiv2::ByteOrder) const /home/hongxu/FOT/exiv2/src/exif.cpp:358:48
    #8 0x7f022fca17f9 in Exiv2::TiffImage::readMetadata() /home/hongxu/FOT/exiv2/src/tiffimage.cpp:196:18
    #9 0x55b70c in Action::Print::printSummary() /home/hongxu/FOT/exiv2/src/actions.cpp:288:16
    #10 0x55a19a in Action::Print::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/hongxu/FOT/exiv2/src/actions.cpp:248:48
    #11 0x532dcb in main /home/hongxu/FOT/exiv2/src/exiv2.cpp:166:29
    #12 0x7f022e1deb96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #13 0x435ac9 in _start (/home/hongxu/FOT/exiv2/install/bin/exiv2+0x435ac9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/hongxu/FOT/exiv2/install/bin/exiv2+0x511969) in __sanitizer::internal_memmove(void*, void const*, unsigned long)
==10074==ABORTING
```

**Comment by piponazo** [comment]
I tried to reproduce this issue on master but I could not. I get the following:

```
15:36 $ bin/exiv2 ../../exiv2Pocs/npe_w_value.cpp_212_1.tiff 
Exiv2 exception in print action for file ../../exiv2Pocs/npe_w_value.cpp_212_1.tiff:
invalid memory allocation request
```

Could you double check?

**Comment by HongxuChen** [comment]
It weird that I cannot reproduce this issue either.
I was using our fuzzer ([to appear](https://2018.fseconference.org/event/fse-2018-demonstration-fot-a-versatile-configurable-extensible-fuzzing-framework)) to instrument on `exiv2` firstly, but I remember I replayed with the asan instrumented clang-6.0 later. Now only the fuzzer instrumented version (5940c6f) reports NULL pointer write. Maybe I was replaying with the wrong binary.

The weird thing is that I was thinking the fuzzer's instrumentation， which is quite similar to [AFL's](http://lcamtuf.coredump.cx/afl/technical_details.txt), won't bring false positive for NULL pointer write when instrumented together with ASAN. I will investigate this.

For now, I just close this issue since it's not reproducible for any instrumented `exiv2` as of 59e84ed.

**Comment by D4N** [comment]
I haven't tested this myself, but I'd just like to add, that commit
5940c6f is not in master yet. It is on the branch
disable-printStructure, which I advised @hongxu to use instead of
master, so that their fuzzer won't report bugs in printIFDStructure.

**Comment by HongxuChen** [comment]
@D4N I mentioned in the last sentence that I tested 59e84ed which is not reproducible; therefore I think it's reasonable to close for now.

**Comment by D4N** [comment]
Yes, you have tested this on 59e84ed, but your original report is
against 5940c6f. Those are different commits, the first one is on master
and the second one is on the branch disable-printStructure.

I have just tested this on disable-printStructure with the first
reproducer (npe_w_value.cpp_212_1.tiff) and I get an error with UBSAN:

/usr/include/c++/8/bits/stl_algobase.h:368:23: runtime error: null pointer passed as argument 1, which is declared to never be null

Maybe your fuzzer was picking this up?

Imho this is still valid.
