### ISSUE TITLE
Running the Test Suite on MinGW builds

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#469]
The procedure to run the test suite is documented in README.md in the "RC1" branch.  It works for Cygwin and I've documented a successful approach for Visual Studio Builds (ugly, however it works).

I'm running the suite with this command:
```
564 rmills@rmillsmm-w7:~/gnu/github/exiv2/exiv2/build $ export EXIV2EXT=.exe ; export EXIV2BINDIR=${PWD}/bin ; make tests
```

Using MinGW python and MinGW Bash (and build) results in:
```
Traceback (most recent call last):
  File "runner.py", line 48, in <module>
    system_tests.configure_suite(conf_file)
  File "/home/rmills/gnu/github/exiv2/exiv2/tests/system_tests.py", line 178, in configure_suite
    rel=rel_path)
ValueError: Path replacement for exiv2: /home/rmills/gnu/github/exiv2/exiv2/tests/C:/msys64/home/rmills/gnu/github/exiv2/exiv2/build/bin/exiv2 does not exist (was expanded from C:/msys64/home/rmills/gnu/github/exiv2/exiv2/build/bin/exiv2)
make[5]: *** [Makefile:115: newtests] Error 1
...
```
Using DOS python and MinGW bash (and build) results in:
```
Traceback (most recent call last):
  File "runner.py", line 48, in <module>
    system_tests.configure_suite(conf_file)
  File "/home/rmills/gnu/github/exiv2/exiv2/tests/system_tests.py", line 178, in configure_suite
    rel=rel_path)
ValueError: Path replacement for exiv2: /home/rmills/gnu/github/exiv2/exiv2/tests/C:/msys64/home/rmills/gnu/github/exiv2/exiv2/build/bin/exiv2 does not exist (was expanded from C:/msys64/home/rmills/gnu/github/exiv2/exiv2/build/bin/exiv2)
make[5]: *** [Makefile:115: newtests] Error 1
...
$
```
There's something not correct about how the suite is determining the location of exiv2.exe

He's correct that `/home/rmills/gnu/github/exiv2/exiv2/tests/C:/msys64/home/rmills/gnu/github/exiv2/exiv2/build/bin/exiv2` and `/home/rmills/gnu/github/exiv2/exiv2/tests/C:/msys64/home/rmills/gnu/github/exiv2/exiv2/build/bin/exiv2` do not exist.  However why is he searching there?

One other little _**nit**_.  The environment string EXIV2_EXT doesn't feel necessary.  If the suite finds a file exiv2.exe, he knows EXIV2_EXT=='.exe'.  If he finds an executable file exiv2, he knows EXIV2_EXT=''

@D4N I'm happy to run tests on Windows while you make suggestions about changing the python.  I'm sure we'll fix this in a few minutes together on Slack.

**Comment by clanmills** [comment]
We need to get this fixed.  I spent time on this two weeks ago in Scotland.  The problem is in the Python code.  However, I didn't solve it and forgot about this.  When Gilles reported #468 I rediscovered this issue.

**Comment by clanmills** [comment]
You've analysed it correctly.  From memory, I think the error arises from: `os.path.join(_parameters["suite_root"], rel_path)`

There's a fix.  There's always a fix.

It's OK on Cygwin/msvc/Linux/MacOS-X.  We only need to fix it on MinGW.  However it's important to fix it because I believe we want to only use python and refactor/remove the bash scripts.  We need to enable `$ make tests` to run to completion on MinGW.  Amazingly, the elderly bash scripts, such as test/icc-test.sh are working fine.  It's the python that not functioning correctly on MinGW.

**Comment by clanmills** [comment]
I'm not sure how/why this is resolved.  The test suite is running correctly on MinGW32 and MinGW64 on the buildserver.  And it's working fine on both my laptop and desktop machines.  Case closed.
